### ISSUE TITLE
client.py: AttributeError: "'collections.deque' object has no attribute 'maxlen'"

### ISSUE THREAD

**Issue by RuudWolters** [googlemaps/google-maps-services-python#100]
> /usr/lib/python2.6/site-packages/googlemaps/client.py(213)_get()->None
-> if self.sent_times and len(self.sent_times) == self.sent_times.maxlen:
(Pdb) r
AttributeError: "'collections.deque' object has no attribute 'maxlen'"
> /usr/lib/python2.6/site-packages/googlemaps/places.py(87)places()
-> return client._get("/maps/api/place/textsearch/json", params)

**Comment by stephenmcd** [comment]
Fixed in b453ed5b350093a3ac65d7853da61effb08f34c2 and released in 2.4.2
