### ISSUE TITLE
Cannot display directions result

### ISSUE THREAD

**Issue by regiov** [googlemaps/google-maps-services-python#104]
Hi,

Am I correct that by restricting the return value of the directions response to ["routes"], this new restricted response cannot be used to display the result back in a GoogleMaps canvas of a web page?

I know this can be done with direct call to the service in javascript, as demonstrated here: http://jsfiddle.net/user2314737/u9no8te4/ but I was wondering if I could do something similar using the Python library.

Thanks!

**Comment by rbouchez** [comment]
Hi,

Maybe too late for you, but you can use the "overview_polyline" field of a route, or the "polyline" field of a step to do that. Those fields are dictionaries with a "points" key whose value is an encoded path, which can then be decoded (with the geometry library [1]) and displayed on a JS API map (with a Polyline [2]).
Of course you will need to use the Google Maps JavaScript API or Static Maps API to display anything.

==
E.g. with JS: google.maps.geometry.encoding.decodePath("m|peFp_ejVDAr@OnE_AlB_@r@KfASPEPENGLCnD}@n@MRGXIRIROLIJGDCBAB?B?B?B?B?x@J@?@?NBF@@?R@@?D@J?@@v@DV@");
var flightPath = new google.maps.Polyline({
    path: path
});
flightPath.setMap(map);
map.setCenter(path[0]);

Or with Static Maps:
https://maps.googleapis.com/maps/api/staticmap?size=400x400&path=enc:m|peFp_ejVDAr@OnE_AlB_@r@KfASPEPENGLCnD}@n@MRGXIRIROLIJGDCBAB?B?B?B?B?x@J@?@?NBF@@?R@@?D@J?@@v@DV@&<your credentials>
==

[1] https://developers.google.com/maps/documentation/javascript/3.exp/reference#encoding
[2] https://developers.google.com/maps/documentation/javascript/3.exp/reference#Polyline

**Comment by domesticmouse** [comment]
@regiov I'm confused as to what you are attempting to do. This feels like a StackOverflow question...

**Comment by regiov** [comment]
Thanks, @rbouchez, I used essentially the same approach and managed to store routes into a postgis database and then display them on a web interface. The library is working fine for me.

@domesticmouse, all I wanted to do was to use this Python library on the server side to get the itinerary (which I happen to store on a database) and then display the result on a web page. I got a bit confused about why the library returned only a subset of the directions response. If it was the complete response, it could be directly used as input to a DirectionsRenderer object from the google maps javascript library for display. I thought it would make more sense to ask the question here, as it's related to the library design.

**Comment by domesticmouse** [comment]
@regiov from memory, the part of the response we trim is just the request status, i.e. whether the response was OK or the error text. If we are trimming more than that, then that is a bug. I'm unsure about your statement about being able to feed the result directly to the google maps javascript library, as at the very least you would need to add in the geometry library to be able to decode the encoded polylines in the directions result.

Can you show which API call you were attempting to make through the python client library? I'm intrigued now =)

**Comment by regiov** [comment]
Hi @domesticmouse, you can actually display directions without the geometry library. In this example: http://jsfiddle.net/user2314737/u9no8te4/ you can see that a DirectionsRenderer object (represented by the variable directionsDisplay) can take as input the full response from a directions call. So in this specific case, if you don't provide the complete data structure, it doesn't work - even if you're just omitting "status" or other optional parts like "geocoded_waypoints". I asked the question because if the library returned the full response, then it could be used in this scenario, and I was a bit confused about this. But as I said, I managed to do what I wanted following a very similar approach to what @rbouchez suggested, and I'm happy with the library.

**Comment by domesticmouse** [comment]
Thanks for the clarification @regiov. I too would take the approach outlined by @rbouchez
