### ISSUE TITLE
not possible to get API Keys 

### ISSUE THREAD

**Issue by mabodo** [googlemaps/google-maps-services-python#105]
I'm not sure if this is the proper place to post this, but when I try to connect to:

https://developers.google.com/console

Google loads forever and most likely returns a white webpage.
Is this still the place to ask for it? Is somebody else experimenting this issue also?

I got also problems at https://console.developers.google.com/

**Comment by domesticmouse** [comment]
It's working for me on both of the above URLs. Can you dig into your browser developer tools to get more information on what is happening?

Btw, the appropriate forum for bugs on these API end points is https://code.google.com/p/gmaps-api-issues/

Thanks!

**Comment by mabodo** [comment]
It's working now, I guess I hit some downtime. 

Thanks!
