### ISSUE TITLE
Why return unicode json data?

### ISSUE THREAD

**Issue by Folyd** [googlemaps/google-maps-services-python#106]
Hi guys,i used Places python service to request data,but server always return data which is unicode format. how can i switch to utf8? thanks :)

here are my brief code:
```python
    gmaps = googlemaps.Client(key="my_key")
    places_result = gmaps.places(name, location, radius)["results"]
    print places_result
```

here are my result data:
`[{u'rating': 4.7, u'name': u'Eiffel Tower', u'reference': u'CmRgAAAApTX1NmumYAMYE-tVzc-ZNIhArMBb_bnKHsVGlW_CyXvRtsZ_P7wvfFwcME2CDKlBCTLFAajTYzs08ZxPlLtMCEsNhXywzntz7c4fJHz0XQq08tTss3QpidkmQ0vy4JtuEhB1vw0uCZWm9K1yQNsx9phsGhQiAoJK0M2O-tjy703cxvsOCoufUQ', u'geometry': {u'location': {u'lat': 48.85837009999999, u'lng': 2.2944813}}, u'opening_hours': {u'weekday_text': [], u'open_now': False}, u'place_id': u'ChIJLU7jZClu5kcR4PcOOO6p3I0', u'formatted_address': u'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France', u'id': u'fd0cfb424bbd79bf28a832e1764f1c2aa5927714', u'types': [u'premise', u'point_of_interest', u'establishment'], u'icon': u'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png'}]`

**Comment by Folyd** [comment]
After i dive into the source code,i found the find a wired problem.
in `client.py` line 235 of `_get_body()` function,`body = resp.json()` return the json which encoded by unicode format.

here is my screenshot:
<img width="1424" alt="screen shot 2016-01-09 at 8 27 34 pm" src="https://cloud.githubusercontent.com/assets/3369694/12216059/376f3f34-b710-11e5-8824-23299024b063.png">

**Comment by stephenmcd** [comment]
This is working as expected.

If you reframe your question in terms of what you're trying to do and why this is preventing you from doing it, it might be easier to help you.
