### ISSUE TITLE
Google has disabled the use of APIs from this API project. Why?

### ISSUE THREAD

**Issue by Folyd** [googlemaps/google-maps-services-python#107]
Hi guys,why i cannot access the place api after i enable bill account to my project? when i request the api,the server return such a error!

```json
 {
"error_message": "Google has disabled the use of APIs from this API project.",
"html_attributions": [ ],
"results": [ ],
"status": "REQUEST_DENIED"
}
```

**Comment by rbouchez** [comment]
Hi Folyd. Late reply, but I don't think this is in the scope of this library: as the error message state, there seems to be a problem with your API project itself.

In such cases there should be a useful error message visible in the [Developers Console](https://console.developers.google.com/), where the projects are managed. For example it is possible that your project has raised a Terms of Service violation flag, and as a consequence has been automatically suspended. Not sure what happened specifically in your case though.

**Comment by williamknn** [comment]
@rbouchez I think it's not a project issue. My system make requests to retrieve geolocation data and since yesterday, sometimes, we receive this same error. The system didn't changed anything that could broken this, until yesterday, it was working very well, thanks. And Developers Console doesn't show any error.

**Comment by rbouchez** [comment]
@williamknn : this API response comes directly from the API, so if you receive exactly the same error at least this is a priori not an issue in this lib. You might want to open a ticket in Google's public tracker, under the Geolocation API component:
https://issuetracker.google.com/issues/new?component=188847&template=788015

Please note that "REQUEST_DENIED" status can refer to different error_message s. If your error_message is exactly the same, then your project should have at least its Geolocation API disabled.
If you have a different error_message, then I'd advise to carefully look at it, and check your requests accordingly.

Also, you might want to double-check that you are using the correct project, that the Geolocation API was not disabled recently, and that it has a non-null quota (in the quota tab):
https://console.cloud.google.com/apis/api/geolocation.googleapis.com/overview?project=<your_project_id>
