### ISSUE TITLE
out of daily quota requests must not be retried, they must be immediately failed instead

### ISSUE THREAD

**Issue by gae123** [googlemaps/google-maps-services-python#109]
The library keeps retrying requests that are rejected by the REST API with the following. I think this is not correct behavior. It masks what exactly is happening from the the python API developer and it does not matter how long you retry it will keep failing until the next day.

{u'status': u'OVER_QUERY_LIMIT', u'rows': [], u'error_message': u'You have exceeded your daily request quota for this API.', u'destination_addresses': [], u'origin_addresses': []}

![image](https://cloud.githubusercontent.com/assets/6157123/12247122/67175ad4-b867-11e5-9efb-0a0921006bd5.png)

**Comment by andybarilla** [comment]
Are there plans to pull this into the repo?

**Comment by dvndrsn** [comment]
I agree. It seems counter intuitive for the client to retry when the daily quota is expended. This should be the responsibility of the consumer of the API client.

**Comment by tpcarneiro** [comment]
Sorry for the dumb question, but how can I catch the _RetriableRequest() exception in my code so I can switch my keys and keep the requests going?
I appreciate if anyone could help me with this matter.

**Comment by stephenmcd** [comment]
@tpcarneiro that would be against the terms of service: https://developers.google.com/maps/terms#section_10_4

**Comment by kerrick-lyft** [comment]
+1 on this request. We recently had an outage due to this issue.

**Comment by kerrick-lyft** [comment]
I opened a PR to fix this issue:
https://github.com/googlemaps/google-maps-services-python/issues/109
