### ISSUE TITLE
Example doesn't work with python 3.5

### ISSUE THREAD

**Issue by BeOleg** [googlemaps/google-maps-services-python#112]
Code:
```python
import googlemaps
from photobase import settings_base

gmaps = googlemaps.Client(key=settings_base.GOOGLE_MAPS_KEY)

# Geocoding an address
geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')

print(geocode_result)
```

Error:
```bash
/Users/olegbelousov/.virtualenvs/photo/bin/python /Users/olegbelousov/Library/Preferences/PyCharm50/scratches/scratch
Traceback (most recent call last):
  File "/Users/olegbelousov/Library/Preferences/PyCharm50/scratches/scratch", line 7, in <module>
    geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')
  File "/Users/olegbelousov/.virtualenvs/photo/lib/python3.5/site-packages/googlemaps/geocoding.py", line 68, in geocode
    return client._get("/maps/api/geocode/json", params)["results"]
  File "/Users/olegbelousov/.virtualenvs/photo/lib/python3.5/site-packages/googlemaps/client.py", line 223, in _get
    result = self._get_body(resp)
  File "/Users/olegbelousov/.virtualenvs/photo/lib/python3.5/site-packages/googlemaps/client.py", line 246, in _get_body
    body["error_message"])
googlemaps.exceptions.ApiError: REQUEST_DENIED (An internal error was found for this API project.)
```

EDIT:
All other addressed I've tested worked fine

**Comment by halkun** [comment]
Hi @BeOleg 

I was able to run this on my machine with Python 3.5 without any issues.
Were you able to resolve this?

Ensure you have activated API for "Google Maps Geocoding API" on https://console.developers.google.com

Here is my output when printing geocode_result:

> [{'formatted_address': '1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA', 'address_components': [{'types': ['street_number'], 'short_name': '1600', 'long_name': '1600'}, {'types': ['route'], 'short_name': 'Amphitheatre Pkwy', 'long_name': 'Amphitheatre Parkway'}, {'types': ['locality', 'political'], 'short_name': 'Mountain View', 'long_name': 'Mountain View'}, {'types': ['administrative_area_level_2', 'political'], 'short_name': 'Santa Clara County', 'long_name': 'Santa Clara County'}, {'types': ['administrative_area_level_1', 'political'], 'short_name': 'CA', 'long_name': 'California'}, {'types': ['country', 'political'], 'short_name': 'US', 'long_name': 'United States'}, {'types': ['postal_code'], 'short_name': '94043', 'long_name': '94043'}], 'place_id': 'ChIJ2eUgeAK6j4ARbn5u_wAGqWA', 'types': ['street_address'], 'geometry': {'location_type': 'ROOFTOP', 'viewport': {'southwest': {'lng': -122.0856793802915, 'lat': 37.4209882197085}, 'northeast': {'lng': -122.0829814197085, 'lat': 37.4236861802915}}, 'location': {'lng': -122.0843304, 'lat': 37.4223372}}}]
