### ISSUE TITLE
Add check for maximum URL length of a request

### ISSUE THREAD

**Issue by wwwald** [googlemaps/google-maps-services-python#113]
Currently working with the Elevations API, and I noticed that some of my bigger requests (single request, lots of points) returned with a HTTPError, status code 400. After checking the  [API docs](https://developers.google.com/maps/documentation/elevation/intro#ElevationRequests) and some testing, this seems to be an URL length issue: request URLs are limited to "about 2000 characters, after URL Encoding".

It seems that the `googlemaps` module (or at least the `Client`'s `elevation()` method does not perform a check on this URL length. My only option, currently, is to find the "sweet spot" in the number of points per request that will make sure the URL length stays below the limit, and use that number to split up my Elevation API requests.

Is auto-handling URL length something that could be built in?

**Comment by stephenmcd** [comment]
Thanks for bringing this up. 

We decided not to implement breaking long elevation requests into multiple parts since it could have hidden costs against a user's quota. What I have done though is modified elevation requests to use [polyline encoding](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) which should result in much shorter URLs:

86e38dd2a760f6236354fd0d750563d58a5d54db

Could you give this a try and see how effective it is in your case?

**Comment by wwwald** [comment]
Completely agree on the quota argument - it's something I had to take into account when working around the URL problem earlier on.

I wasn't aware of the possibility of encoded polylines in the URL. Great solution, I'll try it out as soon as possible.

**Comment by stephenmcd** [comment]
Please let me know how it goes.

**Comment by wwwald** [comment]
After some more usage... I'm currently down to about 350 points max per API request, but that still is too much in some cases. It seems that the polyline length after encoding is pretty unpredictable, even with a limit of 350 points I sometimes run into HTTP errors because of too long URL's.

I haven't yet looked at how the polyline encoding actually works - so I'm not sure what exactly triggers longer URL lengths in those specific cases. For now, I'll just lower my limits further.

**Comment by wwwald** [comment]
I'm currently down to a limit of 380 points per request, that seems to be a number that ensures that 99% of the polyline-encoded URLs stay within the URL length limit.

I haven't looked at the remaining 1% in detail, so it's unclear what exactly makes the polylines run longer in those cases.
