### ISSUE TITLE
Where can I find the "status" code of a response?

### ISSUE THREAD

**Issue by wwwald** [googlemaps/google-maps-services-python#116]
I'd love to differentiate between if a Directions API request with status "OK" or status "ZERO_RESULTS". But, the `response` does not include this status field.

This status code is inspected in [`client.py` on line 239](https://github.com/googlemaps/google-maps-services-python/blob/master/googlemaps/client.py#L237), but never stored in a response.

Can I find it somewhere else? Or is this something that could be considered to be added to the response, as returned by `googlemaps.Client`?

**Comment by domesticmouse** [comment]
You can differentiate `OK` from `ZERO_RESULTS` by inspecting the length of the result, zero returned objects is `ZERO_RESULTS`. The reason we inspect is that both `OK` and `ZERO_RESULTS` are successful results, while everything else are failure conditions that we need to throw error conditions on.

**Comment by JonHannah** [comment]
This tripped me up too: I handled ApiErrors which I assumed would include status="ZERO_RESULTS", so hit KeyErrors when I tried to access the results. On reviewing the [docs](https://developers.google.com/maps/documentation/geocoding/intro#StatusCodes) I see it is clearly noted that 

> "ZERO_RESULTS" indicates that **the geocode was successful** but returned no results. This may occur if the geocoder was passed a non-existent address.

Perhaps it might help to re-emphasise this within the python client readme?
