### ISSUE TITLE
Just curious if there are any plans to support the Geometry API?

### ISSUE THREAD

**Issue by weallcock** [googlemaps/google-maps-services-python#120]
The title pretty much says it.  I had a small application I wanted to do for personal use.  I would have preferred python since I know it, but I needed the Geometry API, so I also got to get my feet wet with javascript :-).

**Comment by domesticmouse** [comment]
It seems to me outside of the remit of the Google Maps Web Services client library for Python. Doing calculations on latitude and longitudes should really be usable with any backend API, no?

**Comment by weallcock** [comment]
My apologies, but I don't completely follow what you are saying.  The Google Map web services have a geometry library and it is my (perhaps incorrect) impression, that this project was intended to provide python access to the google map APIs, so I am not sure why you would say it is out of scope?  As to your second comment on calculations with latitude and longitude, I can't tell if you simply stating a point of view or if you are saying such things are already possible within the other APIs?  In my specific case, I want to calculate the heading between points and then find the point that is a specific distance along that heading.  The way that I found to do that was via the Geometry API.  Is there another way?

**Comment by stephenmcd** [comment]
@weallcock The JavaScript API provides geometry (https://developers.google.com/maps/documentation/javascript/geometry) - are you referring to that? It's different from the Maps Web Services (https://developers.google.com/maps/web-services/) which is what this client library is for.

**Comment by johnrbnsn** [comment]
Hi @stephenmcd ,

I'd like to second that request for the geometry API here (same one in the Javascript you linked). I'm currently using the Javascript API on my front end, but back end is in Python (Django) and I would prefer to do all my post-processing on the back end. Could this feature be added to the Python library, or is there a way to call the javascript geometry API via Python (I was thinking an HTTP request via requests library, but that doesn't seem possible from javascript documentation).

Thanks for your help, sorry to revive a closed issue!
