### ISSUE TITLE
Problem with client._get

### ISSUE THREAD

**Issue by njs94** [googlemaps/google-maps-services-python#121]
Traceback (most recent call last):
  File "geo.py", line 46, in <module>
    geocode("API_KEY")
  File "geo.py", line 44, in geocode
    return client._get("/maps/api/geocode/json", params)["results"]
**AttributeError: 'str' object has no attribute '_get'**

_**Please can anyone resolve this error, I'm trying this from past 2 days but i'm not able to figure it out.**_

**Comment by domesticmouse** [comment]
Please refer to my answer to #122
