### ISSUE TITLE
Help!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by njs94** [googlemaps/google-maps-services-python#122]
Please anyone let me know how to use this **availble codes**.
I'm finidng it difficult to configure.

Thanks in advance... :+1:

**Comment by njs94** [comment]
@broady ASAP pls.....

**Comment by domesticmouse** [comment]
I'm not even sure where you are starting from. Are you a Python developer? Can you write Python command line apps? Have you installed `pip`? Can you set up project dependencies? I suspect a Q&A site like https://stackoverflow.com/ may be a better starting point for you.

**Comment by njs94** [comment]
Thank you @domesticmouse.

I'm new to python( 2months), I've installed pip, but yes i ain't able to setup the dependencies.
I ain't able to figure it out where to insert my api key, which function to call from which program, how to handle the dependencies.

pls, can you let me know how to compile atleast one of the program and get the output required 'cause there are 2 files namely googlemaps and test so I'm confused which to compile or edit.


Thanks in Advance.
