### ISSUE TITLE
requests-2.10

### ISSUE THREAD

**Issue by 0-wiz-0** [googlemaps/google-maps-services-python#124]
Please add support for requests-2.10.
Some packaging systems already use that version.

On the other hand, is this project dead? https://github.com/googlemaps/google-maps-services-python/issues/107 still is unanswered.

**Comment by rbouchez** [comment]
Changed requests' max version to 2.10.0 in #132 

As for #107, this is a bit outside of the scope of this library, since the error message states there is a problem with the API project itself. I will leave a comment there for future reference.
