### ISSUE TITLE
radius = 300

### ISSUE THREAD

**Issue by romkaqua** [googlemaps/google-maps-services-python#125]
Hello.
I'm post request:
result = gmaps.places(message.text, location=(source_latitude,source_longitude), radius = 300, language = "ru')
But places in variable "result", more than 300m. I'm confused :(
Thank you.

**Comment by rbouchez** [comment]
Hi romkaqua! In fact the "radius" argument doesn't guarantee that the results with be inside it.

Cf. the [documentation](https://developers.google.com/places/web-service/search#TextSearchRequests):

> radius — Defines the distance (in meters) within which to bias place results. The maximum allowed radius is 50 000 meters. Results inside of this region will be ranked higher than results outside of the search circle; **however, prominent results from outside of the search radius may be included**.
