### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by chadadair72** [googlemaps/google-maps-services-python#126]
Recommend clarifying in the documentation that even when units is specified as imperial, the returned value for distance is still measured in meters. This could result in a miscalculation. Example below:
u'rows': [{u'elements': [{u'distance': {u'text': u'149 mi', u'value': 240318}

**Comment by domesticmouse** [comment]
I'm curious which documentation you are suggesting we make this clarification in. I can't see anything in the documentation supplied with this client library that specifies the meaning of the results, so I'm guessing you are talking about the documentation on [https://developers.google.com/maps/]? If yes, can you please submit feedback on the specific page you want clarified, using the "Send Feedback" button?

This has the advantage of logging the bug with our tech writers with sufficient detail that they can actually fix the problem. Thanks!
