### ISSUE TITLE
channel error

### ISSUE THREAD

**Issue by EXPEnbansal** [googlemaps/google-maps-services-python#127]
gmaps = googlemaps.Client(client_id='id', client_secret='secret-No=',channel='channel')
     
TypeError: __init__() got an unexpected keyword argument 'channel'

**Comment by rbouchez** [comment]
Hi EXPEnbansal, are you using the version 2.4.3 of the library? The channel was added in a later commit I think.
(check the available arguments with `>> help(googlemaps.Client)`)

**Comment by EXPEnbansal** [comment]
Yes that is still not on pip , when I pip install googlemaps that it install the version which does not have channel,kindly upload new package which has channel parameter

**Comment by rbouchez** [comment]
If you want you can also install the package as is it currently on the master branch, with the following command:
pip install git+git://github.com/googlemaps/google-maps-services-python@master
This should give you the channel parameter.

Side note: as it is currently on master, you can only use the channel arg if you don't use the key arg at all. I submitted a new pull request to correct that (i.e. allow channel when client ID and key are both used).
