### ISSUE TITLE
api client 'reverse_geocode' does not support place_ids

### ISSUE THREAD

**Issue by avukonke** [googlemaps/google-maps-services-python#136]
The Google Maps Reverse Geocoding service allows for the retrieval of a place's address details based on a place_id. The current implementation does not support this feature of the Geocoding service.

There are no methods builtin to over-ride the default query which is done based on lat/lng co-ordinates.

Currrently the only way to support this functionality of the Geocoding service is to refactor the existing code, with my local implementation being able to do do both, with a place_id receiving a higher priority if included in the args, else the default lat/lng lookup.

Was the excluion of queries by place_id, a conscious design decision.

I think this feature should have been included, considering Google's value outlook on place_id's vs any other metric for addressing place's in the Geocoding service.

File: googlemaps/geocoding.py:71

**Comment by stephenmcd** [comment]
If you look at the current version on Github you'll see this has since been implemented, there just hasn't been a release since then. You can either install directly from Github, or wait for a new release which I'll do soon.

**Comment by stephenmcd** [comment]
2.4.4 is released now

**Comment by avukonke** [comment]
Perfect, thanks. I'll update as necessary, open new issues for other things that I might encounter in daily use of the product.
