### ISSUE TITLE
Allow user to append several values for same component filter type

### ISSUE THREAD

**Issue by mkrebber** [googlemaps/google-maps-services-python#138]
It would be nice to allow several values for same component type. 
Use case: You may want to filter sublocalities via locality component type ("locality matches against both locality and sublocality types") and in addition you may restrict result set by another locality.

Maybe we should extend converting components by defaultdict containing lists?

**Comment by stephenmcd** [comment]
The client library supports whatever the web services do, so this isn't an issue with the client library itself.

There's a corresponding issue to have multiple component values for the web services here: https://code.google.com/p/gmaps-api-issues/issues/detail?id=4233

**Comment by mkrebber** [comment]
Thank you for your response.

Im pretty sure Google's geocoding API already supports several values for locality component, here is an example. First request will return 2 results, second request will return only one result restricting first result set by additional locality (locality:Hannover). 

https://maps.googleapis.com/maps/api/geocode/json?components=locality:Burg|administrative_area:NDS|country:Deutschland&key={KEY}

https://maps.googleapis.com/maps/api/geocode/json?components=locality:Burg|locality:Hannover|administrative_area:NDS|country:Deutschland&key={KEY}

**Comment by stephenmcd** [comment]
Sorry, you're right! 

Thanks for pointing that out, I've re-opened the issue.

**Comment by mkrebber** [comment]
@stephenmcd This feature comes in very handy, PR looks good. Thanks a lot.

**Comment by stephenmcd** [comment]
You're welcome, thanks for raising the issue.
