### ISSUE TITLE
distance matrix not working for middle east Asia region

### ISSUE THREAD

**Issue by aaannuujj** [googlemaps/google-maps-services-python#140]
I have been trying distance matrix function in googlemaps. it is working for many regions across world like London,New York, Hyderabad, Dublin etc but not working for Jeddah,Riyadh,Muscat,Cairo etc. For these regions i am getting JSON output as ZERO RESULT. What could be the problem and how to fix it?
Thanks
Anuj

**Comment by stephenmcd** [comment]
Can you provide a specific query that isn't working as expected?

**Comment by stephenmcd** [comment]
I'll close this for now since it's presumably a data related issue with the web service, not the client library.
