### ISSUE TITLE
Invalid directions

### ISSUE THREAD

**Issue by esfomeado** [googlemaps/google-maps-services-python#144]
Hi,

Origin = 41.149516,-8.6102671
EndPoint = 41.149617,-8.610742

I'm using this for getting the directions from here 41.149516,-8.6102671 to 41.149617,-8.610742
Although this work fine on the website:
https://www.google.pt/maps/dir/41.149516,-8.6102671/41.149617,+-8.610742/@41.1495393,-8.6129531,17z/data=!3m1!4b1!4m6!4m5!1m0!1m3!2m2!1d-8.610742!2d41.149617

In the API returns the origin point instead of the endpoint since the distance between them is really close so my program gets stuck in an infinite loop.
I'm using the walking mode.

Regards

**Comment by rbouchez** [comment]
Hi esfomeado,

This looks more like an issue related to the Directions API than to this Python library.

I'd like to make a note that results from the Google Maps APIs and the Google Maps application are not guaranteed to always be the same. In this case, the grey path visible in Google Maps is not an information we get from the APIs. What could be compared is the blue path you can see here:
https://www.google.com/maps/dir/41.1496343,-8.6102228/41.1492487,-8.6106511/@41.1492568,-8.6109525,189m/data=!3m1!1e3!4m2!4m1!3e2?hl=en

Directions request:
https://maps.googleapis.com/maps/api/directions/json?origin=41.1496343,-8.6102228&destination=41.1492487,-8.6106511&mode=walking
