### ISSUE TITLE
new user question: where does the API go?

### ISSUE THREAD

**Issue by pkchehal** [googlemaps/google-maps-services-python#146]
Hello, I am a relatively new Python user and very new to github. I was wondering if someone can help me figure out how I can use the code to extract distance calculations in Python posted here. In particular, the requested input arguments refer to a client and not to an individual users API key. While all other arguments that require user entry are clearly documented there is no mention of where the API goes. Perhaps it's something really obvious that I can't tell, any advice.

**Comment by markmcd** [comment]
Ahh - you need to create a 'client' but you can do so by passing an API key. e.g. in the first example on the project README (copied below), you can replace the 'Add Your Key here' string with your API key, e.g. AIzAaSdFAsdFASDf... You can then re-use that client for each request.

```python
import googlemaps
from datetime import datetime

gmaps = googlemaps.Client(key='Add Your Key here')

# Geocoding an address
geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')

# Look up an address with reverse geocoding
reverse_geocode_result = gmaps.reverse_geocode((40.714224, -73.961452))

# Request directions via public transit
now = datetime.now()
directions_result = gmaps.directions("Sydney Town Hall",
                                     "Parramatta, NSW",
                                     mode="transit",
                                     departure_time=now)
```
