### ISSUE TITLE
Distance Matrix: Allow user to provide function to select element or elements from matrix

### ISSUE THREAD

**Issue by markmcd** [googlemaps/google-maps-services-python#15]
i.e.

def get_quickest(a, b):
  return a["duration"] < b["duration"]

matrix.get_element(get_quickest) # returns the smallest element

And something similar for selecting entire columns / rows. I've not put much thought into how these selectors would work, so let's discuss options here.

**Comment by rbouchez** [comment]
Do you still want to provide helpers around the Web Services responses? I'd like to work on that, but not sure what the interface would be. Something like this?
```
>> import googlemaps.helpers
>> helpers.dma_shortest_duration(dma_response)
```
or would we prefer to wrap the responses directly?
```
>> dma = googlemaps.distance_matrix(origins=["foo"], destinations=["bar"])
>> dma.__class__ # <class 'googlemaps.distance_matrix.DMAResponse'>
>> dma.get_shortest_duration()
```

**Comment by araichev** [comment]
I recently made a tiny and simple collection of helpers geared towards my work, which you can find  [in this Github reop](https://github.com/araichev/googlemaps_helpers).
One of the helper functions converts a distance matrix response to a Pandas DataFrame, which you can then easily filter.
