### ISSUE TITLE
Update requests to 1.11.x

### ISSUE THREAD

**Issue by bartmika** [googlemaps/google-maps-services-python#151]
Currently when running

```python
pip install googlemaps
```

I noticed it will uniintstal my ``request 1.11.x`` library and replace it with ``request 1.10`` library. Can we change this so this library uses the latest library?

**Comment by bartmika** [comment]
May you please update:

```python
requirements = [
    'requests<=2.11.0',
]
```

at this file location?

https://github.com/googlemaps/google-maps-services-python/blob/master/setup.py

**Comment by rodolfomartinez** [comment]
+1

**Comment by bartmika** [comment]
I have just ran ``googlemaps`` with ``request 2.11.1`` and I confirm it is working.
