### ISSUE TITLE
distance matrix timeout

### ISSUE THREAD

**Issue by leonardoo** [googlemaps/google-maps-services-python#152]
hi, when i use distance matrix with from (19.51377166, -99.147045), to (19.70320955235589, -99.0872863769531) the request return a exception timeout

client.distance_matrix(
(19.51377166, -99.147045), 
(19.70320955235589, -99.0872863769531), "transit", False, units="metric")

<a href="http://i.imgur.com/fbl3XDG.png">
  <img src="http://imgur.com/fbl3XDGl.png" />
</a>

**Comment by stephenmcd** [comment]
Works for me: 

```
>>> client.distance_matrix((19.51377166, -99.147045), (19.70320955235589, -99.0872863769531), "transit", False, units="metric")
{u'status': u'OK', u'rows': [{u'elements': [{u'status': u'ZERO_RESULTS'}]}], u'origin_addresses': [u'19.513772,-99.147045'], u'destination_addresses': [u'19.70321,-99.087286']}
```

Perhaps it's an intermittent network issue on your end.

**Comment by pavan04patel** [comment]
Did that, works once and the second time I run my script it errors.
