### ISSUE TITLE
Request: Get Real Lat/Lon from StreetView Images

### ISSUE THREAD

**Issue by GianniCristian** [googlemaps/google-maps-services-python#154]
Dear All,

I have looked at the library and I didn't find a way to recover the exact Lat/Long from a streetview images. I understand that is possible through JavaScript using the command below:

`google.maps.StreetViewService().getPanoramaByLocation()`

Unfortunately I could not find a way to do the same using Python. Theoretically, using the URL to retrieve the image, the obtained one is the closest to the requested point but there is no info available on the real lat/long. Maybe is already implemented something in this library but I didn't find it.

Thanks!

**Comment by stephenmcd** [comment]
This library is merely a wrapper for the Google Maps Web Services found here: https://developers.google.com/maps/web-services/

Those don't contain any integration with streetview data, so it's out of scope here.
