### ISSUE TITLE
Async Support?

### ISSUE THREAD

**Issue by owaaa** [googlemaps/google-maps-services-python#156]
Are there any plans for async support?

**Comment by justinwp** [comment]
This is difficult to implement currently as we still support python 2.7.  I will be taking a look at the current implementation around client.session to see if an interface can be established that would allow support of async. See https://github.com/googlemaps/google-maps-services-python/issues/224#issuecomment-373935633

**Comment by P-E-B** [comment]
Hi, it's been many years and the client still has no compatibility with async calls. aiohttp would be very helpful.
