### ISSUE TITLE
Client is not thread-safe as of 2.4.5

### ISSUE THREAD

**Issue by Deewiant** [googlemaps/google-maps-services-python#160]
The changes in commit 32d07dfa make the client no longer thread-safe. Something like the following seems to fail every time after some seconds:

```python
from concurrent.futures import ThreadPoolExecutor
import googlemaps
gmaps = googlemaps.Client(key=key)
pool = ThreadPoolExecutor(max_workers=20)
list(pool.map(lambda x: gmaps.distance_matrix(origins=[(50, 5)], destinations=[(50, 5)]), range(100)))
```

With the following error:

```python
.../lib/python3.5/site-packages/googlemaps/client.py in wrapper(*args, **kwargs)
    336         args[0]._extra_params = kwargs.pop("extra_params", None)
    337         result = func(*args, **kwargs)
--> 338         del args[0]._extra_params
    339         return result
    340     return wrapper

AttributeError: _extra_params
```

With 2.4.4, it works fine.

Perhaps `Client` isn't intended to be thread-safe, but that should at least be documented somewhere.

**Comment by stephenmcd** [comment]
Thanks for reporting this. It's the result of an undocumented/unsupported feature, so I think it will suffice to just swallow the exception for now, would should get things working with multiple threads again.
