### ISSUE TITLE
convert.location_list only accepts list of string locations, not tuples

### ISSUE THREAD

**Issue by willjschmitt** [googlemaps/google-maps-services-python#162]
Right now, if the provided argument to location_list is a tuple, it assumes it has to be a lat/long pair, rather than possibly a tuple of string locations. For a sequence of string locations, it thus needs to use a non-list datatype. Perhaps a further type check on the length and contents of the tuple could indicate if it should be interpreted as a lat/long or not?

**Comment by stephenmcd** [comment]
Well it wouldn't be a type check per say, we'd need to inspect the individual elements and check if they contains commas indicating they're lat/lng pairs. 

That aside, I really feel like this area of the library goes way too far in terms of accepting arguments in different formats and trying to munge them consistently, so I would like to avoid continuing in that direction.

Thanks anyway.

**Comment by willjschmitt** [comment]
I think that's fair. Shouldn't it be more reasonable, though, for the default behavior to interpret as a list of items to pass directly to the API, rather than taking a quick glance, seeing its a tuple, then assuming it must be a lat/long? I see more of the API looks to interpret a sequence of locations to be a list using `_list` as a suffix in the names, so I suppose I probably should interpret that more literally rather than reading that as a "iterable". Given that, I suppose its pretty reasonable for the consistent interpretation of tuples to be lat/lng pairs in the cases where arguments could be lists of locations.

Thanks for the quick reply!

**Comment by stephenmcd** [comment]
> Shouldn't it be more reasonable, though, for the default behavior to interpret as a list of items to pass directly to the API, rather than taking a quick glance, seeing its a tuple, then assuming it must be a lat/long?

It might certainly be more reasonable - but since the current approach has existed for quite some time, presumably people are depending on that already, so not worth changing.

**Comment by willjschmitt** [comment]
Agreed. Perfect. Thanks!
