### ISSUE TITLE
Session Sharing

### ISSUE THREAD

**Issue by apt142** [googlemaps/google-maps-services-python#163]
When using this in setting where I need to make a lot of calls in quick succession. I'm seeing a performance issue with all the stopping and starting of clients connections.

If there was a way to start a session and re-use it for each connection, it would cut down the time spent fetching information dramatically.

It doesn't seem like it would be too hard augmenting the Client init to take in a passed session variable for re-use.

Is there any interest in this?

**Comment by stephenmcd** [comment]
Using requests' sessions for connection pooling sounds like a good idea, so go for it.

One thing to keep in mind is that by default the client will rate limit requests to 10 per second, so you may be hitting that hard limit.

**Comment by apt142** [comment]
Are you referring to the google api's request limit? 

If so, that's fine.

**Comment by stephenmcd** [comment]
Yeah, but the client actually enforces it - it won't make any requests over the limit.

**Comment by apt142** [comment]
I'm currently using the API with a very high rate limit and this seems to be the bottle neck in performance. 

Thanks for being so easy going!  Here's the pull request:

https://github.com/googlemaps/google-maps-services-python/pull/164
