### ISSUE TITLE
Street View (metadata & imagery) API Support?

### ISSUE THREAD

**Issue by jyunis** [googlemaps/google-maps-services-python#172]
Hi there,

I need to interface with the Street View API -- specifically the ability to query street view coverage areas by GPS location -- and I'm wondering if you have any plans to add support for this feature.

If not, I'll gladly build the module and submit a PR down the road when it's working/tested.

**Comment by stephenmcd** [comment]
The server-side client libraries here on Github are merely wrappers for each of the Google Maps Web Services, which doesn't include anything covering Street View APIs.

You're most likely looking for the client-side JavaScript library for Street View APIs: https://developers.google.com/maps/documentation/streetview/intro

**Comment by jyunis** [comment]
Thanks for the response.

Yes, I understand what this library does and I was wondering if there were any plans to support wrapping the Street View APIs, as I need to access that API in Python. Seems that answer is "no".
