### ISSUE TITLE
Arrival Time not allowed with traffic model

### ISSUE THREAD

**Issue by mikeklinker129** [googlemaps/google-maps-services-python#176]
When you specify the arrival time (without a departure time) and a traffic model, returns an error.

This should return the 'duration_in_traffic', along with the standard fields. 

arrival_time works fine as long as you do not specify a traffic model (and do not want the travel time with traffic...)

**Comment by stephenmcd** [comment]
That sounds like an issue with the web service itself, not this client library.

Issues for the webservice are tracker in the Google issue tracker, and it looks like this has already been reported there: https://issuetracker.google.com/issues/35828380

Please star the issue there to vote for it.
