### ISSUE TITLE
Support of position sharing service

### ISSUE THREAD

**Issue by Almtesh** [googlemaps/google-maps-services-python#177]
Hi,
I can't understand how to use this library to user position sharing service that is in Google Maps, like described in this help: https://support.google.com/maps/answer/7326816
If it's not possible, can you help me to find how to do this?
Regards.

**Comment by stephenmcd** [comment]
This client library only covers the Google Maps Web Services listed here: https://developers.google.com/maps/web-services/

Location sharing isn't related to those.

**Comment by Almtesh** [comment]
Thanks for the answer, @stephenmcd, but my question was not only to know if it's possible with this library, I'm still looking for a way to do this. I have nowhere to ask, so if a answer could be available somewhere, I will be happy, please…
