### ISSUE TITLE
How to use client id and client secret in snap to road api?

### ISSUE THREAD

**Issue by gopalmeena** [googlemaps/google-maps-services-python#184]
Hello everyone,
I have a enterprise edition of google map key. So i have client-secret value(private crypto key) and client id. So i initialized client with 
googlemaps.Client(client_id=value_of_client_id,client_secret=value_of_client_secret)
But wile using snap to road api, it gives error "Must provide API key for this API. It does not accept enterprise credentials" .
I don't have any api key . So can some one guide me how can i use client id and client key for this api?

**Comment by stephenmcd** [comment]
See https://developers.google.com/maps/documentation/roads/get-api-key
