### ISSUE TITLE
Road snap some points not returned

### ISSUE THREAD

**Issue by jheld** [googlemaps/google-maps-services-python#189]
Some of the paths that I send to the road snap API do not come back as I would expect.

If for instance I pass in X number of coordinate pairs (interpolate is on, btw), and I receive Y pairs back, where Y > X, I may not receive all of my originalIndex pairs back.

So, I may have on the return: 
`[{originalIndex: 0}, new_0, new_1, new_2, {originalIndex: 3}, ...]`

What does this behavior mean? And what should I do with the pair(s) that are not returned from the API?

**Comment by hmhtb** [comment]
I’m looking to develop a software which gives the user the ability to extract the street view frames of the roads all over the US by searching the road name and the longitude coordinates of the road. Furthermore, I need to save the snapshots on an online cloud or a computer hard drive. I know I have to use google map API.

**Comment by jheld** [comment]
Is there any word on this?

Again the problem is that some points from the original set may not be returned on the response.

**Comment by hmhtb** [comment]
no unfortunately. waiting for some one to answer!

**Comment by justinwp** [comment]
Sorry for the delay in answering. Do you have a reproducible example of this? If not I'll attempt to recreate.

**Comment by jheld** [comment]
Hi,

I have no current examples but I may be able to try again in the next
couple of weeks.

I ended up building an algorithm around the issue as best as I could.
Mostly around ordering valid input points around the ones not present but
were in the input. So I keep track of all of the original indices/items and
cross reference when the sorting is needed.

Might sound a bit complex, the way I'm describing it. But yes if the
library would handle the work for me, it would be easier to parse most
likely.
