### ISSUE TITLE
Error in speed_limits method

### ISSUE THREAD

**Issue by mahimranjan** [googlemaps/google-maps-services-python#190]
Hi,

I'm getting this error when trying to use the speed_limits method:

Traceback (most recent call last):
  File "testurl.py", line 38, in <module>
    speed_lim = gmaps.speed_limits("ChIJVQcunKIA3IAReSI1GXlR1Yk")
  File "/Library/Python/2.7/site-packages/googlemaps/client.py", line 356, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/googlemaps/roads.py", line 95, in speed_limits
    extract_body=_roads_extract)["speedLimits"]
KeyError: 'speedLimits'

I think I'm making the call correctly. Here is how I'm calling it:
speed_lim = gmaps.speed_limits("ChIJVQcunKIA3IAReSI1GXlR1Yk")

Everything else (directions) seems to be working fine. 

Thanks

**Comment by stephenmcd** [comment]
Looks like you're using a place ID that doesn't have a corresponding speed limit, eg here's a valid one:

https://roads.googleapis.com/v1/speedLimits?placeId=ChIJLQcticc0GQ0RoiNZJVa5GxU&key=YOUR_KEY

**Comment by mahimranjan** [comment]
Oh wow. Just my luck that the first street I tried doesn't have speed limits in Google database!

Surprising, this is a major interstate freeway.

**Comment by mahimranjan** [comment]
Should this really error out? I can deal with this with a try/except clause, but it doesn't seem right that this should error out like this.

Maybe add a check in the library and return a success/failure flag?

**Comment by stephenmcd** [comment]
You're right, I fixed that in de0ddab13e423b3ab4708e5b21b23206a3887dd3
