### ISSUE TITLE
Ignoring command for transit

### ISSUE THREAD

**Issue by Andreilys** [googlemaps/google-maps-services-python#196]
For some reason or another, my directions results occasionally ignore the mode of transit, and instead give walking directions. From my understanding its because its faster to walk then to wait for the bus, but I'd still rather get bus directions. Right now i'm handling it like this:
```
    def get_next_bus(self):
        gmaps = googlemaps.Client(key=GOOGLE_MAPS_API_KEY)
        now = datetime.now()
        directions_result = gmaps.directions(HOME,
                                         WORK,
                                         mode="transit",
                                         departure_time=now)
        try:
            #reformat the departure time so that we can subtract it later from current time
            departure = directions_result[0]["legs"][0]["departure_time"]["text"]
            return self.get_mins_left(now, departure)
        except:
            return "Faster to walk"
```

But i'd much rather just get the bus times even if its going to be longer than walking

**Comment by stephenmcd** [comment]
See the `transit_mode` and/or `transit_routing_preference` params.
