### ISSUE TITLE
Getting More than 10 Place Photos

### ISSUE THREAD

**Issue by sri3705** [googlemaps/google-maps-services-python#199]
I found that google placedetails feature gives us a maximum of 10 photos for a given place with a place_id. Is it possible to get all the photos for that place, rather than just 10?

**Comment by sri3705** [comment]
I see a similar issue here:

https://github.com/googlemaps/google-maps-services-js/issues/62

This page referenced me to another page:

https://issuetracker.google.com/issues/35830750

I am not sure what is the status of this issue.

**Comment by stephenmcd** [comment]
It's an accepted issue that isn't yet resolved. I'll close this issue, since it's not specific to this library.
