### ISSUE TITLE
get current location with geolocate

### ISSUE THREAD

**Issue by masoudr** [googlemaps/google-maps-services-python#202]
Hi,
I want to get the current location based on [this link](https://developers.google.com/maps/documentation/geolocation/intro) but I can't find any python example to do that. I want to create a general code to get the current location.
I used this part of code but it didn't work.
```
import googlemaps
gmaps = googlemaps.Client(key='my_key')
loc = gmaps.geolocate()
print(loc)
```
Thanks.

**Comment by domesticmouse** [comment]
You need to supply Wifi and Cell tower information for the Geolocate API to do it's job. From the [documentation](https://developers.google.com/maps/documentation/geolocation/intro): The Google Maps Geolocation API returns a location and accuracy radius based on information about cell towers and WiFi nodes that the mobile client can detect.

**Comment by masoudr** [comment]
I'already test that but I couldn't retrieve the information. is there any example to do this?
Another problem is I want to create a general purpose app that is independent on some information. For example, works on any wifi router or cellular network.

**Comment by domesticmouse** [comment]
Extracting the WiFi and Cell tower information is platform specific and outside the scope of the API. You may be better off using the geolocation APIs available on specific platforms, e.g. [Web](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation), [iOS](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html) and [Android](https://developer.android.com/training/location/index.html).

**Comment by masoudr** [comment]
Thanks,
But I want to create a python script to retrieve current location of the user and it must be independent of wifi or cellular information, I mean something like web API but in the python script.
There is no example for python API for geolocation.

**Comment by forwhomthebelltools** [comment]
Hello @masoudr, maybe you have to disable geocoding API form google console and leave geolocation api enabled. In this way your script will run  and you will get location with accuracy in meters. I tried your python script above but the position returned is non accurate, because of geolocation by ip address.

**Comment by masoudr** [comment]
@forwhomthebelltools Thanks for the tip. I tried the manual method and sent POST request directly to googleapi and it worked somehow.

**Comment by masoudr** [comment]
@trinanda I couldn't get any result from `googlemaps` API. If you need the location you can use [google doc](https://developers.google.com/maps/documentation/geolocation/intro) and manually send a request with a proper body to the server and get the location.

**Comment by joeljogy** [comment]
Hey, here's a different solution to the same problem and you can obtain more accurate geolocation(lat,lng coordinates) using selenium. 

Tutorial for that can be found here: https://link.medium.com/LOSOvlDLiU

Or find the script for it, directly here: https://github.com/joeljogy/Getting-GeoLocation

**Comment by jenlincode** [comment]
@joeljogy This is perfect. Thank you for your solution.

**Comment by markmelnic** [comment]
> Hey, here's a different solution to the same problem and you can obtain more accurate geolocation(lat,lng coordinates) using selenium.
> 
> Tutorial for that can be found here: https://link.medium.com/LOSOvlDLiU
> 
> Or find the script for it, directly here: https://github.com/joeljogy/Getting-GeoLocation

This is a cool but very unsustainable solution.
