### ISSUE TITLE
python API does not provide STATUS code?

### ISSUE THREAD

**Issue by rbelew** [googlemaps/google-maps-services-python#203]
new to this API, but it seems it provides only the 'results' value shown here https://developers.google.com/maps/documentation/geocoding/ ?  how can i get the status code?

**Comment by a-sansom** [comment]
Same situation here,  and I was wondering the same thing.

Looks to be due to `geocode()` method returning just the `results` portion of the response. See:

https://github.com/googlemaps/google-maps-services-python/blob/2.5.1/googlemaps/geocoding.py#L68

**Comment by stephenmcd** [comment]
One of the goals of the client library is to abstract away the need for checking status.
