### ISSUE TITLE
Support Geocode by PlaceId

### ISSUE THREAD

**Issue by spaceraccoon** [googlemaps/google-maps-services-python#207]
geocode() does not support geocoding by placeId while reverse_geocode does.

**Comment by stephenmcd** [comment]
This isn't an issue with the client library since it simply implements whatever the web service provides:  https://developers.google.com/maps/documentation/geocoding/intro

**Comment by fr-davis** [comment]
Seems like this has been supported recently.
Node JS implementation is already done.
https://github.com/googlemaps/google-maps-services-js/pull/413
