### ISSUE TITLE
Plotting?

### ISSUE THREAD

**Issue by AntreasPetsas** [googlemaps/google-maps-services-python#211]
Hello, there.
Thank u for this shortly introduction to google maps services using python.
I want to ask u if there is any way to plot coordinates data using this service.

**Comment by linevich** [comment]
I guess you should use [Maps JS API](https://developers.google.com/maps/documentation/javascript/overlays) if you want to plot something on the map. 
This library is to retrieve data (geocoding, calculating distance, etc) that you can save into the database and then render on your webpage using JS.

**Comment by AntreasPetsas** [comment]
Hi, and thank you for response.
The API you have referred is for javascript. Is it something similar for python(2.7 or over 3)?

**Comment by linevich** [comment]
Google Map is rendering by JS so answer is no.

**Comment by lukelu0520** [comment]
google staticmap can make it with python
