### ISSUE TITLE
Autocomplete does not allow filtering by administrative_area

### ISSUE THREAD

**Issue by teddyward** [googlemaps/google-maps-services-python#216]
[This line of documentation](https://github.com/googlemaps/google-maps-services-python/blob/69d80691bf0b262fbb5a18593891a01183dc29e3/googlemaps/places.py#L335) claims that one can filter autocomplete results by an 'administrative_area'. Actually doing so, however, causes a 500 error. It seems that the API doesn't accept anything but 'country' as a property of the components parameter.

Preferred solution: squash [this bug](https://issuetracker.google.com/issues/35822067). But it's a P4 :(

Alternatively: just update the docs

**Comment by stephenmcd** [comment]
I've updated the client library to reflect the actual limitations.

**Comment by teddyward** [comment]
Hi Stephen,

Do you know if there are any plans in the works to allow filtering by an `administrative_area`? Hoping for any update on [b/35822067](https://issuetracker.google.com/issues/35822067)

**Comment by stephenmcd** [comment]
I don't have any further info. I suggest subscribing to the issue linked.
