### ISSUE TITLE
places_nearby example usage

### ISSUE THREAD

**Issue by nikhilmishradevelop** [googlemaps/google-maps-services-python#218]
Could anyone please post how do I use the places_nearby feature.
places_result=gmaps.places_nearby(location=(40.714224, -73.961452))
I am getting an api error invalid request

**Comment by mcimpoi** [comment]
This worked for me. 
If I removed radius, I get invalid request.

Hope this helps.

```
gmaps = googlemaps.Client(key=YOUR_API_KEY)
geocode_result = gmaps.geocode('London')
location_ = geocode_result[0]['geometry']['location']
place_results = gmaps.places_nearby(keyword='cafe', location=location_, radius=1000)
```

**Comment by stephenmcd** [comment]
Definitely consult the docs which describe in detail the required and optional parameters:

https://developers.google.com/places/web-service/search
