### ISSUE TITLE
Places search ignores Radius

### ISSUE THREAD

**Issue by pozaylov** [googlemaps/google-maps-services-python#221]
Hi,

Lately i get many results that seems to ignore the Radius parameter.
It was working find until about a week ago.

Any idea if anything has broken?

Btw radar search seems to work fine, but it will be shuts off in few months by Google...

Thanks

**Comment by stephenmcd** [comment]
You haven't specified whether you're referring to text search or nearby search. In either case:

For text search, are you specifying orderby to distance? If so radius is ignored.

For nearby search, prominent places outside the radius may also be included.

Both these behaviours are described in the docs: https://developers.google.com/places/web-service/search

If neither of the above are the case for you, please re-open but be sure to provide more detail about the inputs and outputs.

**Comment by stephenmcd** [comment]
BTW you should also verify you're getting expected results by using CURL or some such tool to make HTTP requests to the API - if the results you get via that are the same, then this isn't an issue with the client library.
