### ISSUE TITLE
Introducing O(log(n)) from O(n) by allowing batch requests

### ISSUE THREAD

**Issue by hammad93** [googlemaps/google-maps-services-python#222]
The current API and Google Maps server only allows processing of one address at a time. We can increase the efficiency of the API by allowing batch requests which reduces the theoretical time complexity from O(n) to O(log(n)) which can be validated using applied performance tests that I have conducted below,

![performance](https://user-images.githubusercontent.com/11673956/36493519-cf893794-16fd-11e8-82a3-ef49d38111f5.png)

As we can see, allowing even a batch size of 11 reduced the runtime from ~1216 seconds to ~123 seconds or a ~9.88 fold increase in efficiency. This can decrease the load of both clients and servers.

**Comment by jkkenzie** [comment]
I am not getting this, as this app is a client, how is it going to do bulk/batch on a server that does not provide batch service? Or do you mean this client becomes the server?

**Comment by hammad93** [comment]
I created an API that was similar to Google Maps API using [Pelias](http://pelias.io/install.html) and was able to implement a bulk processing algorithm. The data shown above was an experiment on different batch sizes on a messy data set size of 22,000 addresses.
