### ISSUE TITLE
Async support like your promise

### ISSUE THREAD

**Issue by 3mp3ri0r** [googlemaps/google-maps-services-python#224]
Hi, I'm looking for your own statement ("Asynchronous or synchronous All requests support synchronous or asynchronous calling style.") in your website [documentation](https://developers.google.com/maps/documentation/geocoding/client-library). I've tried using await but this error occured:
`TypeError: object list can't be used in 'await' expression`

What is the correct way to implement await in googlemaps python client? Or it does not support it at the moment?

**Comment by stephenmcd** [comment]
Thanks for bringing this up - the documentation is indeed misleading as the Python client doesn't support asynchronous requests right now (the others do).

We already have an issue open for this #156 so I'll close this one for now.

**Comment by 3mp3ri0r** [comment]
Will async support added in the near future?

**Comment by hzlmn** [comment]
Sorry for offtop but I started work on asyncio/aiohttp based client for google maps services https://github.com/hzlmn/aiogmaps. It is pretty in progress and not stable yet so any help/review/recommendation would be greatly appreciated. Cheers :)

**Comment by P-E-B** [comment]
Hi, it's been many years and the client still has no compatibility with async calls. aiohttp would be very helpful.
