### ISSUE TITLE
Using bounds in places_nearby

### ISSUE THREAD

**Issue by exterkamps** [googlemaps/google-maps-services-python#226]
In the places class, the function places_nearby uses location+radius to search for places nearby, but in the [places API docs](https://developers.google.com/maps/documentation/javascript/places#place_search_requests) it also documents using a LatLng bounding box as type 'google.maps.LatLngBounds' instead of a location and radius.  But in the places_nearby function location is required and is converted to a latlng in _places:

`    if location:
        params["location"] = convert.latlng(location)`

This makes it seemingly impossible to send a bounding box, as it is not a single lat long, and there is not a param for bounds.  Is there a way to send a bounds object to the API instead of a location + radius with this library?

**Comment by stephenmcd** [comment]
You're looking at the docs for the client-side JavaScript API which is unrelated to this library. The relevant docs are here: https://developers.google.com/places/web-service/search#PlaceSearchRequests

**Comment by AlbertoMCS** [comment]
Hi, 
Thanks for the response.
Same thoughts here. Does that mean that requesting places within a rectangle is not supported by this library?

**Comment by jpoehnelt** [comment]
@AlbertoMCS Correct, you can only specify a location + radius.

>location — The latitude/longitude around which to retrieve place information. This must be specified as latitude,longitude.
radius — Defines the distance (in meters) within which to return place results. The maximum allowed radius is 50 000 meters. Note that radius must not be included if rankby=distance (described under Optional parameters below) is specified.

**Comment by AlbertoMCS** [comment]
Hi Justin, 
Many thanks for clarifying. 
Regards
