### ISSUE TITLE
Given exact lat,lng in places seems like doesnt work

### ISSUE THREAD

**Issue by fatih-koc** [googlemaps/google-maps-services-python#227]
def city2geo (place):
    geocode = gmaps.geocode(place)
    lat = geocode[0]['geometry']['location']['lat']
    lng = geocode[0]['geometry']['location']['lng']
    out = "%s,%s" % (lat, lng)
    return out

query = 'irrigation'
places = gmaps.places(query, geocode, 250)

I am using your excellent library as above but whenever i give some locations to be searched, it returns global responses instead. Maybe i'm using wrong or maybe something is broken but this seems to be a serious.

**Comment by stephenmcd** [comment]
Re-read your code, I don't think your `geocode` variable works the way you intent it to.
