### ISSUE TITLE
place_nearby next page token should not necessitate location

### ISSUE THREAD

**Issue by n0wastaken** [googlemaps/google-maps-services-python#230]
When calling the api with a token extracted from last result

`google_result = gmaps.places_nearby(page_token=token)`

I get this error saying I should stipulate location:

`TypeError: places_nearby() missing 1 required positional argument: 'location'`

But it's actually not the case on the api documentation:

https://developers.google.com/places/web-service/search#PlaceSearchPaging

**Comment by stephenmcd** [comment]
Thanks, fixed in 86cfa452a07a039f942df5e51a410756797b2ac3
