### ISSUE TITLE
Description of how to get an API Key does not seem to correspond to Google API Console

### ISSUE THREAD

**Issue by TimFrance** [googlemaps/google-maps-services-python#236]
The instructions here:
https://github.com/googlemaps/google-maps-services-python#api-keys

do not correspond to what happens here: https://developers.google.com/console

In particular there is no reference to a "Server Key"

**Comment by TimFrance** [comment]
After more searching, I found instruction which work here https://kb.yoast.com/kb/generate-set-google-maps-geocoding-server-key/
This seems to have been updated on 26 May, 2018, so I am guessing that Google must have updated the interface recently

**Comment by nonsignificantp** [comment]
Thanks! this help me alot!

**Comment by justinwp** [comment]
closed by #297
