### ISSUE TITLE
How to prefix via: to waypoints for directions API?

### ISSUE THREAD

**Issue by debugger22** [googlemaps/google-maps-services-python#239]
I read the following doc

```
The duration in traffic is returned only if all of the following are true:

1. The request includes a valid API key, or a valid Google Maps APIs Premium Plan client ID and signature.
2. The request does not include stopover waypoints. If the request includes waypoints, they must be prefixed with via: to avoid stopovers.
3. The request is specifically for driving directions—the mode parameter is set to driving.
4. The request includes a departure_time parameter.
5. Traffic conditions are available for the requested route.
```

For condition 2, how do I prefix `via:` to the waypoints. I have a list of coordinates.

**Comment by debugger22** [comment]
@stephenmcd

**Comment by stephenmcd** [comment]
You can provide the waypoints as a string with `via:` manually prefixed.

**Comment by debugger22** [comment]
Thanks!

**Comment by Allenite** [comment]
Can you provide an example?

... waypoints="via:[(lat1,lon1),(lat2,lon2)]"... returns an ApiError:NOT_FOUND

and 

... waypoints=via:"[(lat1,lon1),(lat2,lon2)]" returns syntax error.  

Can you share an example of how to use waypoints and via: with a list of multiple lat,long waypoints?

**Comment by Allenite** [comment]
I tried this and it works:

... waypoints="via:lat1,lng1|via:lat2,lng2|via:lat3,lng3" ...

**Comment by debugger22** [comment]
I think there should be an example in the documentation.
