### ISSUE TITLE
Tag 3.0.0, 3.0.1, 3.0.2

### ISSUE THREAD

**Issue by peterclearmetal** [googlemaps/google-maps-services-python#246]
Could you tag the 3.0.x releases please?

Also, curious whether 3.0.0 had any breaking changes or if the major version bump for other reasons  

Thanks

**Comment by justinwp** [comment]
I added the tags a couple days ago(see #272) and I am improving the release process #295 to automate it from tags so that this does not occur again.

You can see the diff here: https://github.com/googlemaps/google-maps-services-python/compare/2.5.1...3.0.0
