### ISSUE TITLE
places function doesn't seem to be working properly

### ISSUE THREAD

**Issue by thefuga** [googlemaps/google-maps-services-python#248]
As title says, this function doesn't seem to be working as it should - at least from what documentation says.
I'm passing a query and a location (coordinates) and also informing the radius. The problem is if I pass a radius of 1, 10, 100 or any other value, the function is always returning 20 places with a token for next page, and the next page returns a token to the next.
I'm not sure if this is working as intended, but from Google Places API documentation, it doesn't seem to be.

**Comment by stephenmcd** [comment]
If you check the [documentation for the radius parameter](https://developers.google.com/places/web-service/search) you'll see that it says it controls bias of the results, which wouldn't necessarily affect the number of results as you're expecting.
