### ISSUE TITLE
Question: Get Current Location of device

### ISSUE THREAD

**Issue by hobojoe720** [googlemaps/google-maps-services-python#250]
Hey Guys, 

This is a question to see if the library is as easy as I am hoping. Is it possible to get the location of the client running the Py script easily. Everything I am readying says you need to specify WiFi access points or Cell towers or even an address. 

In effect, I just want to capture the JSON with what is the believed current location much like the following when you accept the location stuff:
https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

Thanks

**Comment by stankovicsrdjo** [comment]
You will have to get location via browser using JavaScript. 

They have native model called 'navigator'. You could get lat and long coordinates using that module and use Python to scrape them.

Here's StackOverflow article about that topic:

https://stackoverflow.com/questions/11787941/get-physical-position-of-device-with-python


I hope I helped you, if I got you wrong let me know !

**Comment by stephenmcd** [comment]
Thanks @stankovicsrdjo
