### ISSUE TITLE
Using API to develop a software to snapshot street view frame by frame along roads

### ISSUE THREAD

**Issue by hmhtb** [googlemaps/google-maps-services-python#251]
I’m looking to develop a software which gives the user the ability to extract the street view frames of the roads all over the US by searching the road name and the longitude coordinates of the road. Furthermore, I need to save the snapshots on an online cloud or a computer hard drive. I know I have to use google map API. 
Thanks

**Comment by XenonR** [comment]
Hello, this doesn't seem to be a technical issue. So most likely nobody here can help you with that.
I would recommend to ask your question again on [https://stackoverflow.com](https://stackoverflow.com).
The issues tracked here are of technical nature regarding the library itself. For example if a specific use case breaks the library.

Best regards.
