### ISSUE TITLE
SSL verify is always True

### ISSUE THREAD

**Issue by zaxcie** [googlemaps/google-maps-services-python#258]
As part of the Client.__init__ method, there is these lines

```
        self.requests_kwargs = requests_kwargs or {}
        self.requests_kwargs.update({
            "headers": {"User-Agent": _USER_AGENT},
            "timeout": self.timeout,
            "verify": True,  # NOTE(cbro): verify SSL certs.
        })
```

Why is verify hardcoded to True? This is causing me some problem.

I would suggest to pass verify as a kwargs and remove the hardcoded aspect.

**Comment by ozcanyarimdunya** [comment]
Yeap it gives ```SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]``` error to me.
