### ISSUE TITLE
how to know if a point is into a polygon

### ISSUE THREAD

**Issue by sadalsuud** [googlemaps/google-maps-services-python#267]
Hi people, I have reading documentation to know if I using this library in python, I can know if a point is into polygon ... Exists a example with JavaScript in documentation de google maps services, but I do not know if this library supports this things. Somebody help me?  Thanks!

**Comment by justinwp** [comment]
Yes, that is a feature of the JavaScript SDK. If you are still having a challenge here I would suggest using [shapely](https://pypi.org/project/Shapely/). See [this stackoverflow answer](https://stackoverflow.com/questions/36399381/whats-the-fastest-way-of-checking-if-a-point-is-inside-a-polygon-in-python) for guidance.
