### ISSUE TITLE
Optimize google api calls

### ISSUE THREAD

**Issue by GoNzCiD** [googlemaps/google-maps-services-python#271]
Hi, I've recently used HommeAssistant component than uses this library to ask Distance Matrix API.

I've noticed in google's API console that receibe request even if origin and destination are the same. It should be possible to avoid consume an API call if you know the result?

Thanks

**Comment by justinwp** [comment]
At this time I would prefer to leave any caching up to the user. If you can elaborate on your specific use case and any latency or others issues you may have, we can reconsider this topic. 

Let me know if you would like an example of caching calls that should be deterministic.

**Comment by GoNzCiD** [comment]
I did an automation script to save the previous position of the tracker, and if it's in the same definited zone (home, work,....) it don't call the service.

This was enought to reduce the API calls.
