### ISSUE TITLE
 Google Maps Street View for a specific date (different years)

### ISSUE THREAD

**Issue by hmhtb** [googlemaps/google-maps-services-python#276]
Google Maps Street View for a specific date (different years)
I am trying to find a way to load the Google Maps Street View for a specific time period by accessing the image date. For example, on google maps it lets you go back as far as 2007. How can I make google load the map from another year instead of the current year?  
Actually, I am trying to find a method to store the Google Maps Street View for a specific time interval by accessing the image date. How can I make Google load the map from another year instead of the current year using API?
I did not find any commend in Google API document. Can you help me with this?
Thanks

**Comment by domesticmouse** [comment]
This is the Python Client library for the Google Maps Web Services. For questions about using the Google Maps APIs support options outlined [here](https://developers.google.com/maps/support/). Thanks!
