### ISSUE TITLE
'ZERO RESULTS' in distance matrix when mode="transit"

### ISSUE THREAD

**Issue by jilladona** [googlemaps/google-maps-services-python#278]
The code works fine when mode="driving", but I get 'ZERO RESULTS' when I specify:

`traffic_result_6pm_NP = gmaps.distance_matrix((origin), (destination),
                                       mode="transit", units="metric",
                                       departure_time=now,
                                       transit_routing_preference="fewer_transfers", region=None)`

**Comment by tjansson60** [comment]
I am having the same problem now, so what was the solution?
