### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by rajasaad7** [googlemaps/google-maps-services-python#279]
Hi,
I was trying to geoloacate myself using python script and want to get exact coordinates from where I am running the script,

I am getting a basic error i.e.

Traceback (most recent call last):
  File "C:/Users/Dexter/PycharmProjects/geotrack/api_integration.py", line 8, in <module>
    gmaps = googlemaps.client(key = API_KEY)
TypeError: 'module' object is not callable

Note : I am using python 3.7 

Regards
Raja Muhammad Saad

**Comment by justinwp** [comment]
Hi Raja,

The below snippet should demonstrate the fix. Please use `googlemaps.Client(key=API_KEY)` instead.

```python
>>> import googlemaps

>>> googlemaps.client(key=API_KEY)  # incorrect
TypeError: 'module' object is not callable

>>> googlemaps.Client(key=API_KEY)  # correct 
<googlemaps.client.Client at 0x7fb524265438>
```

**Comment by likenzy1** [comment]
Hi @rajasaad7 are you still active ? I want to ask you some question about your Cragslist scaper
My telegram @xnngboi
