### ISSUE TITLE
INVALID_REQUEST with next_page_token

### ISSUE THREAD

**Issue by Jesse-jApps** [googlemaps/google-maps-services-python#280]
For some reason an `INVALID_REQUEST` is returned if next page is requested immediately via `next_page_token`. Adding small delay between successive requests solves the problem.

**Comment by alxfed** [comment]
I've just bumped into the same.

**Comment by amuramoto** [comment]
This is expected behavior. There is a short delay between when the page token is generated and when it can be used to paginate.

https://developers.google.com/places/web-service/search#PlaceSearchPaging

**Comment by alxfed** [comment]
Ha-ha-ha! :) 1 second (on average) delay is supposed to be called an 'expected behavior' for an API? Ha-ha-ha! :)
