### ISSUE TITLE
allow pass-through of 'requests' kwargs in apis more generally

### ISSUE THREAD

**Issue by silky** [googlemaps/google-maps-services-python#283]
it would be great to pass through some options to requests; such as for example a value for the `timeout` parameter.

any thoughts on allowing this in general on all the apis? or, less flexibly but still usefully, allowing for a general configuration for all queries?

as an example, it would be great if when calling `.place` we could pass through an additional dictionary of these values, and use them as an arg for `requests_kwargs=...`

thoughts?

thanks!

**Comment by silky** [comment]
still valid

**Comment by jpoehnelt** [comment]
This work is likely not going to occur as we work on gRPC version of this library instead in the second half of 2020. Still waiting on additional protos to be published similar to https://github.com/googleapis/googleapis/blob/master/google/maps/roads/v1op/roads.proto. 

Note that I did rewrite the [Node sibling](https://github.com/googlemaps/google-maps-services-js) of this library to be a light wrapper around Axios(requests equivalent), but I prefer to avoid that here for now.
