### ISSUE TITLE
Bulk API support for Geocoding.

### ISSUE THREAD

**Issue by vineelya** [googlemaps/google-maps-services-python#285]
I have a data-set of 16 Millions for which I will send the address etc to Google Geocoding API and get the lat-longs. Right now we are making an API request for POI by POI, I'm wondering if we can do bulk /batch request, where in which I send around 500 POIs or so, so that we can save some round-trip time. Please advise.

**Comment by domesticmouse** [comment]
I think you will want to have this discussion with [Google Maps Premium Plan team](https://developers.google.com/maps/premium/).
