### ISSUE TITLE
Is there a way to get the location (lat, lng) and address by place_id?

### ISSUE THREAD

**Issue by howiec721** [googlemaps/google-maps-services-python#314]
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

**Comment by jpoehnelt** [comment]
@howiec721 For questions like these you will probably get a faster response on [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) with the `google-maps` tag. But to answer your question, you can get the details of the place with the following `Client.place` call:

```python
>>> import googlemaps

>>> key = "YOUR KEY"

>>> client = googlemaps.Client(key=key)
>>> result = client.place("ChIJmTcPVFEUkFQRJffv_dHRUgE")['result']

>>> print(result['formatted_address'])
>>> print(result['geometry']['location']['lat'], result['geometry']['location']['lng'])

4411 Stone Way N, Seattle, WA 98103, USA
47.6603309 -122.3425122
```
