### ISSUE TITLE
How to use Geolocation API

### ISSUE THREAD

**Issue by venturer1984** [googlemaps/google-maps-services-python#317]
The documentation doesnt seem to tell how to use to the geolocation API.  I tried several formats on how to query the API(using data on this page https://developers.google.com/maps/documentation/geolocation/intro#request_body) But i always keep getting Error 400. Is there a an example on how to feed MAC addresses to this API? I have tried several different formats with no success.

**Comment by jpoehnelt** [comment]
The following works for me:

```python
>>> wifi_access_points = [ 
    {
        "macAddress": "00:25:9c:cf:1c:ac",
        "signalStrength": -43,
        "signalToNoiseRatio": 0
    },
    {
        "macAddress": "00:25:9c:cf:1c:ad",
        "signalStrength": -55,
        "signalToNoiseRatio": 0
    }
  ]
>>> client.geolocate(wifi_access_points=wifi_access_points, consider_ip=False) 

{'location': {'lat': 33.3631308, 'lng': -117.08720749999998}, 'accuracy': 20.0}
```

If you are still having issues, it may be best to start a question on StackOverflow with the `google-maps` tag.
