### ISSUE TITLE
Directions "via"

### ISSUE THREAD

**Issue by gellowmellow** [googlemaps/google-maps-services-python#326]
Hi,

The directions.py does not seem to support "via":

`https://maps.googleapis.com/maps/api/directions/json?
origin=Boston,MA&destination=Concord,MA
&waypoints=Charlestown,MA|**via**:Lexington,MA
&key=YOUR_API_KEY`

> If you'd like to influence the route using waypoints without adding a stopover, add the prefix via: to the waypoint. Waypoints prefixed with via: will not add an entry to the legs array, but will route the journey through the waypoint.

This is useful if we want a response having the traffic details.

> duration_in_traffic indicates the total duration of this leg. This value is an estimate of the time in traffic based on current and historical traffic conditions. See the traffic_model request parameter for the options you can use to request that the returned value is optimistic, pessimistic, or a best-guess estimate. The duration in traffic is returned only if all of the following are true:

> The request does not include stopover waypoints. If the request includes waypoints, they must be prefixed with via: to avoid stopovers.

Reference: https://developers.google.com/maps/documentation/directions/intro

**Comment by jpoehnelt** [comment]
closing in favor of #239 

It is currently possible to specify waypoints already prefixed with via as a work around.
