### ISSUE TITLE
Documentation and pip metadata not updated to reflect lack of python 2 support

### ISSUE THREAD

**Issue by peterjwest** [googlemaps/google-maps-services-python#345]
On version 4.0.0 onwards

- The readme says "Requirements: Python 2.7 or later".
- `setup.py` does not have a `python_requires='>=3.5',` (or similar) rule

**Comment by jpoehnelt** [comment]
closed via https://github.com/googlemaps/google-maps-services-python/commit/e27988ecef8139f45c93a306a4b83834ebb35f37

**Comment by peterjwest** [comment]
Thank you! 

Is there any chance you could add the `python_requires` rule?
Because package managers such as Poetry use this data to decide what versions of the package to install based on your python version.

**Comment by peterjwest** [comment]
Thanks!
