### ISSUE TITLE
Feature request - COVID 19

### ISSUE THREAD

**Issue by jhennig3** [googlemaps/google-maps-services-python#352]
Many State and local county health departments have been putting together long lists of potential places that individuals may have had contact with infected persons, so as to help individuals know to self quarantine. I was wondering if there is a way to take all of that location and time data and make a google map that includes all of it, and a user could see all the days of the month/week on it where possible contact occured?

**Comment by arriolac** [comment]
Hi @jhennig3, that's certainly a tool you can build using GMP tools (including this library). We also have a program where we give GMP credits to support crisis response programs like the use-case you mentioned. You can learn more on our [Public Programs](https://developers.google.com/maps/billing/public-programs) page.
