### ISSUE TITLE
Restrict reverseGeocoding results by postalCode

### ISSUE THREAD

**Issue by LivC182** [googlemaps/google-maps-services-python#354]
I have a list of lat and lng from which I want generate real addresses. However, I would like to restrict the responses to address in a postal code and/or country. If I try : componentRestrictions with geocoding location it doens't work (as per instructions here): https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingRequests
I looked at the actual code of reverseGeocode in here:
https://github.com/googlemaps/google-maps-services-python/blob/master/googlemaps/geocoding.py
It looks like the the function can take ``` result_type``` and ``` location_type ``` as restrictors but I do not understand the syntax. This is my line of code:
```
#javascript
const reverseGeocode = await googleMapsClient.reverseGeocode({ latlng: { lat: randomLat, lng: randomLng }, location_type:[country=GB]} ).asPromise()
#python 3.7
reverse_geocode_result = gmaps.reverse_geocode((random_lat, random_lng), result_type=['country=GB'] )
``` 
with the error:
```
for javascript
message: 'in property "location_type": at index 0: not one of "ROOFTOP", "RANGE_INTERPOLATED", "GEOMETRIC_CENTER", "APPROXIMATE"',
  name: 'InvalidValueError'
for python
HTTPError: HTTP Error: 400
```
Ok so i managed to understand how restrictions work and it dosen't look like reverseGeocode can be restricted to one country/postal_code. Can you confirm that ?
```
const reverseGeocode = await googleMapsClient.reverseGeocode({ latlng: { lat: randomLat, lng: randomLng }, result_type:'street_address'} ).asPromise()
```

**Comment by jpoehnelt** [comment]
>Ok so i managed to understand how restrictions work and it dosen't look like reverseGeocode can be restricted to one country/postal_code. Can you confirm that?

Just checked and this is correct. It doesn't make sense to provide that as a user supplied filter because there is already sufficient information from the lat/lng.
