### ISSUE TITLE
Getting Picture from LatLong or Address

### ISSUE THREAD

**Issue by Kunal2341** [googlemaps/google-maps-services-python#355]
I was hoping to get a picture using google API. Right now I am using 

```
gmaps = googlemaps.Client(key='MYKEY')
geocode_result = gmaps.places_photo('<ANY_ADDRESS>',100,100)
```

But this returns 
<generator object Response.iter_content.<locals>.generate at 0x000002388A5C67C8>

Does anyone know how to convert this return type to a picture? Or am I doing something wrong? Is there another method for us to get the image of any location. 

I just need the image from address or lat long. 
Is there something I need to enable through google API?

**Comment by Kunal2341** [comment]
So any help?

**Comment by jpoehnelt** [comment]
You will need to write the data to a file.

```python
f = open(local_filename, 'wb')
for chunk in client.places_photo(photo_reference, max_width=100):
    if chunk:
        f.write(chunk)
f.close()
```

**Comment by Kunal2341** [comment]
Thanks so much for the help. But when I run the code to a text file I get this 

400. That’s an error.
Your client has issued a malformed or illegal request. That’s all we know.

Do you know why?

**Comment by Kunal2341** [comment]
Also what should I input as `photo_reference`

**Comment by jpoehnelt** [comment]
The photo reference will be returned by another place call. You will have to use that to retrieve the photo.
