### ISSUE TITLE
Places: find place returning just 1 result when using rectangle

### ISSUE THREAD

**Issue by LeonardoFurtado** [googlemaps/google-maps-services-python#362]
when I search for places using a rectangle, the search always returns only 1 place, would this be a bug?

- Windows 10
- lib version: 4.3.1
#### Steps to reproduce

  1. ?

#### Code example

```python
import googlemaps
import json
import pprint
import time

API_KEY = '-----------------'


gmaps = googlemaps.Client(key = API_KEY)

places_result  = gmaps.find_place(input = ['restaurant'], input_type = 'textquery', location_bias = 'rectangle:-1.4442856,-48.4953997|-1.4418506,-48.4937157')

print(places_result)
```
expected output:
dictionary with possible candidates within the rectangle area.

output:
```
{'candidates': [{'place_id': 'ChIJnf-eeLyOpJIRacGmaHEVI8k'}], 'status': 'OK'}
```

**Comment by jpoehnelt** [comment]
Try using `places`  with a radius instead. See https://googlemaps.github.io/google-maps-services-python/docs/index.html#googlemaps.Client.places

**Comment by LeonardoFurtado** [comment]
> 
> 
> Try using `places` with a radius instead. See https://googlemaps.github.io/google-maps-services-python/docs/index.html#googlemaps.Client.places

I currently use radius, I would like to change it to a rectangle.

**Comment by jpoehnelt** [comment]
The API doesn't support a rectangle unfortunately. Going to close this as there is no action item for this repository and library.
