### ISSUE TITLE
Link to test folder in README.md is broken

### ISSUE THREAD

**Issue by majdukovic** [googlemaps/google-maps-services-python#363]
Currently link to the test folder in the README.md (in sentence "For more usage examples, check out the tests.") points to 404 page: https://github.com/googlemaps/google-maps-services-python/tree/master/googlemaps/test

It should point to: 
https://github.com/googlemaps/google-maps-services-python/tree/master/tests

**Comment by jpoehnelt** [comment]
Thanks for reporting. Fixed!

**Comment by majdukovic** [comment]
Thanks for a quick fix Justin.
