### ISSUE TITLE
Update urlib2 to urllib.request in the documentation

### ISSUE THREAD

**Issue by AthulMuralidhar** [googlemaps/google-maps-services-python#367]
- The current best practices page for using the Google api to the google maps interface's python client uses `urllib2` this has been discontinued in the python 3 version to `urllib.request`
- Doc changes are required to reflect this change
- the relevant url is here: https://developers.google.com/maps/documentation/geocoding/web-service-best-practices#BuildingURLs

**Comment by jpoehnelt** [comment]
Thanks for reporting! I have a fix in the works. I'm going to close this as it is not related to this repository.
