### ISSUE TITLE
Please improve on the documentation.

### ISSUE THREAD

**Issue by theKoladeAkande** [googlemaps/google-maps-services-python#372]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

 **Is your feature request related to a problem? Please describe.**

 **Describe the solution you'd like**

 **Describe alternatives you've considered**

 **Additional context**

**Comment by MumblingFumbler** [comment]
The Python documentation found here:
https://googlemaps.github.io/google-maps-services-python/docs/index.html
does not include the static_maps() API. Users must look at the code to figure
out how to use it. Also, there are 0 Python complete examples or use cases about
how to use the googlemaps module in a Python environment--only a couple of
code fragments.

**Comment by jpoehnelt** [comment]
@MumblingFumbler and others,

 Sorry the lack of response here. I am working from the bottom up with an OpenAPI specification for these APIs. You can view it at https://github.com/googlemaps/openapi-specification.

As the spec stabilizes I plan to followup with autogenerating client libraries and hope to replace this one which has become outdated.

**Comment by virajvaidya** [comment]
Bump! The documentation for the Python Client is not up to par, there3 are no code examples anywhere.

**Comment by suryakapurothu** [comment]
Hey @jpoehnelt @theKoladeAkande @virajvaidya @sanga 
Anything that needs to be done here?
Please advise me on the work and I'll try and fix it up.

**Comment by wangela** [comment]
I've noticed that [docs](https://googlemaps.github.io/google-maps-services-python/docs/index.html#) haven't been generated since 3.0.2 and we're now on 4.9.0. 

We've now added a [docs.yml](https://github.com/googlemaps/google-maps-services-python/blob/master/.github/workflows/docs.yml) workflow but it hasn't been run yet.

**Comment by wangela** [comment]
Found the [static_map() docs](https://googlemaps.github.io/google-maps-services-python/docs/index.html#googlemaps.Client.static_map), the error didn't prevent them after all.
