### ISSUE TITLE
No support for Rankby in Places API?

### ISSUE THREAD

**Issue by jrmistry** [googlemaps/google-maps-services-python#376]
**SETUP**
API: Google Places API
OS: Python Google Colab Notebook
Library version: Whatever is the current version when you pip install googlemaps

**CORE PROBLEM:**
Currently in the Google Map's Places API documentation there is supposed to be an option for [rankby parameter](https://developers.google.com/places/web-service/search?hl=en_GB#PlaceSearchRequests), however in this current Python library googlemaps/google-maps-services-python I do not see that as an option at all.

Can someone please inform me if it is possible to change the rankby in the places API using this Python library?

**My code:**
```
!pip install -U googlemaps
import googlemaps

import time

gmaps = googlemaps.Client(key='my_api_key')

list_results = []

result = gmaps.places(
    query = 'lodging',
    type = 'lodging',
    region = 'cn',
    location = '22.150928, 113.563960',
    language = 'en',
)

list_results.extend(result['results'])

while 'next_page_token' in result.keys():
    time.sleep(3)

    result = gmaps.places(query='lodging', type = 'lodging', page_token= result['next_page_token'])
    list_results.extend(result['results'])
```

**Comment by abdelmaoula-99** [comment]
Hi!
i had the same issue with the rankBy in places API
after some research i finally find it, here is an example
`places_result  = gmaps.places_nearby(location='your location', rank_by = 'distance', keyword = 'keyword')`
