### ISSUE TITLE
How to define a basic request in places_nearby function

### ISSUE THREAD

**Issue by ezequias** [googlemaps/google-maps-services-python#379]
Hi

I would like to know how to set basic fields in places_nearby function.

I just want to know if a place of a type exist in a buffer, nothing more than that.

Thank you
Ezequias

**Comment by Tomply87** [comment]
Hi,

I would like to know how to set Contact fields in place_nearby function.

Thanks

Anthony Tata

**Comment by viroos** [comment]
I'm not sure if this is a question or feature request. It looks like there is no option to specify fields in places_nearby function.

And since by default contact and atmosphere data are included. Since this can generated unwanted costs I would even consider this as a bug report not a future request.

**Comment by shuuji3** [comment]
According to the documentation, it looks like that we cannot specify fields for the Nearby Search feature:

> Nearby Search and Text Search return all of the available data fields for the selected place (a subset of the supported fields), and you will be billed accordingly There is no way to constrain Nearby Search or Text Search to only return specific fields. To keep from requesting (and paying for) data that you don't need, use a Find Place request instead.

Ref. [Place Search  |  Places API  |  Google Developers](https://developers.google.com/maps/documentation/places/web-service/search#PlaceSearchRequests)

So I think we cannot implement the `fields=` parameter, unfortunately. If we need to narrow the returned fields, we have to use `find_place`.
