### ISSUE TITLE
Viewport Biasing not working for Asian Countries

### ISSUE THREAD

**Issue by joshTheECE** [googlemaps/google-maps-services-python#396]
Hello. Our team is trying to introduce bias into the Google API Geocoder by introducing the bounds parameter. We tried to use it for Western Country addresses and it worked! However, when we try to geocode "Toledo", when we introduce a bias with the bounding box within the Philippines (specifically in Toledo, Cebu), the result is similar with the no bias geocoding which is Toledo in USA. We tried to use examples from Indonesia too but it the bounding box bias seems to have no effect as well.

If you geocode for "Toledo" only, it returns the Toledo in Ohio, USA. With bounds introduced within the Philippines, the bounds parameter doesn't seem to have an effect. But in fact, there is a Toledo in the Philippines which is in Toledo, Cebu, Philippines. When we used the parameter region='PH' without the bounds parameter, the geocoder led us to the Toledo in the Philippines. So region works but the bounds parameter doesn't.

**Comment by jpoehnelt** [comment]
Can you confirm this is specific to this library by making the same request by building the url manually?

**Comment by jpoehnelt** [comment]
Closing for same reason here: https://github.com/googlemaps/google-maps-services-js/issues/568
