### ISSUE TITLE
 The maximum number of results that can be returned is 60

### ISSUE THREAD

**Issue by HandsLing** [googlemaps/google-maps-services-python#412]
"""
next_page_token contains a token that can be used to return up to 20 additional results. A next_page_token will not be returned if there are no additional results to display. The maximum number of results that can be returned is 60. There is a short delay between when a next_page_token is issued, and when it will become valid.
"""
when i use nearby_search or text_search, why the  maximum number of results that can be returned is 60? Is there any way to get more return?
thx

**Comment by jpoehnelt** [comment]
This is a limitation of the API. Please open a feature request at https://issuetracker.google.com/issues/new?component=188872&template=789309.
