### ISSUE TITLE
Hello Sir, Can I use googleearthengine data on gmaps ?  

### ISSUE THREAD

**Issue by vijaygrg27** [googlemaps/google-maps-services-python#416]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

 **Is your feature request related to a problem? Please describe.**

 **Describe the solution you'd like**

 **Describe alternatives you've considered**

 **Additional context**

**Comment by vijaygrg27** [comment]
I want to show satellite imagery from Google earth engine and show my live location on map

**Comment by datatalking** [comment]
@vijaygrg27 are you asking it to show you walking around on earth from space live... like they show in movies with spy satellites. Or to show your location as a dot on your custom app?

**Comment by vijaygrg27** [comment]
I want to show live location of map like Google Navigation tool. I am doing some research project. I have to collect the ground truth data by visiting the location.

**Comment by vijaygrg27** [comment]
https://openlayers.org/workshop/en/mobile/compass.html

Please check this link. I want to do it through python.

**Comment by datatalking** [comment]
That is probably doable, I'm not seeing an actual code-based question. You will need to create the code and test that out, where you posted a question if for people who have already implemented code and have bugs, errors or challenges at the code level.

**Comment by jpoehnelt** [comment]
This example seems to demonstrate what is desired. https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

**Comment by vijaygrg27** [comment]
Thanks a lot. I want to do it using Python
