### ISSUE TITLE
Can't import googlemaps

### ISSUE THREAD

**Issue by romulocordova** [googlemaps/google-maps-services-python#438]
Hello!

Trying to install `googlemaps` using `!pip3` on Jupyter Notebook is sucessful. But when I import it:

`import googlemaps`

I get this:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/q0/734vk5qj3yj0916mkn7pk9cw0000gn/T/ipykernel_35991/3164823033.py in <module>
----> 1 import googlemaps

ModuleNotFoundError: No module named 'googlemaps'
```

I've read a lot of issues on this one, but I've got no idea on how to solve it.

**Comment by jpoehnelt** [comment]
This issue is not related to this library. You likely need to install the library.
