### ISSUE TITLE
Broken support for Python 3.5

### ISSUE THREAD

**Issue by wdhorton** [googlemaps/google-maps-services-python#449]
#### Environment details

googlemaps 4.7.0
Python 3.5 on Ubuntu

#### Code example

```python
import googlemaps
```

#### Stack trace
 ```
 ../dags/lib/utils.py:3: in <module>
    import googlemaps
../../../miniconda/envs/metropolis_airflow/lib/python3.5/site-packages/googlemaps/__init__.py:20: in <module>
    from googlemaps.client import Client
E     File "/home/circleci/miniconda/envs/metropolis_airflow/lib/python3.5/site-packages/googlemaps/client.py", line 180
E       self.queries_quota : int
E                          ^
E   SyntaxError: invalid syntax
```

I can see that this line was introduced recently in this PR: https://github.com/googlemaps/google-maps-services-python/pull/448

**Comment by sondrelg** [comment]
Python 3.5 reached end of life 2 years ago: https://endoflife.date/python

**Comment by amuramoto** [comment]
Working on fixing this in https://github.com/googlemaps/google-maps-services-python/pull/453
