### ISSUE TITLE
Print output in version 4.7.0

### ISSUE THREAD

**Issue by sondrelg** [googlemaps/google-maps-services-python#451]
https://github.com/googlemaps/google-maps-services-python/pull/448 introduced this line the client initialization:

```python
print("\n","API queries_quota:", self.queries_quota,"\n")
```

Since our codebase contains client initializations, we now see this message printed everytime we do things like:

- Start the server
- Run mypy
- Compile translations
- etc.

Would you accept a PR with a fix, making this an info logger instead?

**Comment by amuramoto** [comment]
Sure! Please send the PR and I'll accept
