### ISSUE TITLE
Add support for new transit information

### ISSUE THREAD

**Issue by markmcd** [googlemaps/google-maps-services-python#61]
http://googlegeodevelopers.blogspot.com.au/2015/01/transit-directions-improvements.html

**Comment by broady** [comment]
Tag as `2.1` or `2.0.1`?

**Comment by markmcd** [comment]
2.1

**Comment by broady** [comment]
Released `2.1`.

**Comment by markmcd** [comment]
There's now some additional information being returned in directions requests covering transit providers. See googlemaps/google-maps-services-java#72

We need to add that too.

**Comment by stephenmcd** [comment]
Don't think there's anything else to do here, since the Python client merely returns JSON (unlike the Java client).
