### ISSUE TITLE
broken auth on payloads containing tilde chars

### ISSUE THREAD

**Issue by shahin** [googlemaps/google-maps-services-python#72]
client.py uses urllib.urlencode, which percent-encodes the tilde character (~) as %7E in order to generate the signature. ~ isn't really a reserved character, so this isn't guaranteed consistent with other URI libraries.

On the other hand, the base_url is encoded via requests in which [the tilde issue](https://github.com/kennethreitz/requests/issues/369#issuecomment-3953802) has [been corrected](https://github.com/kennethreitz/requests/pull/426/files#diff-5956087d5835a57d9ef6fff974f6fd9bR399) and no longer matches urllib's weird behavior.

Ultimately this results in a 403 error (client id omitted below):
```
"Unable to authenticate the request. Provided 'signature' is not valid for the provided client ID, or the provided 'client' is not valid.
The signature was checked against the URL: /maps/api/geocode/json?address=560+Maple+Street+South+%2310~&components=administrative_area%3AMN%7Clocality%3AWaconia%7Cpostal_code%3A55387&client=
If this does not match the URL you requested, please ensure that your request is URL encoded correctly. Learn more: https://developers.google.com/maps/documentation/business/webservices/auth"
```

Although tildes should be rare, ideal behavior would probably be either:

1. Use the same encoding library for the base_url and for computing the authed_url, or
2. Raise an informative exception on disallowed characters (incl. tilde)

instead of waiting for a non-specific 403.

**Comment by stephenmcd** [comment]
Thanks a lot for the detailed report! I've a fix incoming.
