### ISSUE TITLE
Python 3.2.4 ImportError: No module named 'responses'

### ISSUE THREAD

**Issue by scarlettlee** [googlemaps/google-maps-services-python#73]
(Python 3.2.4) ImportError: No module named 'responses'
After I install it, I run the tests, but I see that error. How to solve this?

**Comment by scarlettlee** [comment]
I installed 'responses' to solve the problem

**Comment by domesticmouse** [comment]
Quick question, did you use tox to run the tests?

https://pypi.python.org/pypi/tox

**Comment by scarlettlee** [comment]
No, I used "pip". But there still are some packages I need to download and install myself, like "responses".

**Comment by domesticmouse** [comment]
The README.md, under building, mentions using tox to build and test the library. The testing dependencies are managed by tox via https://github.com/googlemaps/google-maps-services-python/blob/master/test_requirements.txt 

Thanks!

**Comment by scarlettlee** [comment]
Sorry, I still can't get it. I'm rather confused about running the tests.

1) this is a library for calling google map services with python. Am I right?
2) I'm using windows 7. So I don't know how to run the tests by "$ tox" command. The only way I know to run a .py file is right click the file -> Edit with IDLE -> F5.
3) I used "pip install -U googlemaps", "pip install tox" and "pip install [someOtherPackages]" to ensure no errors happen when running the tests like "test_client.py".  In fact, errors still happen when I've finished the steps I mentioned. 
class ClientTest(_test.TestCase):
AttributeError: 'module' object has no attribute 'TestCase'
It messed me up!
4) what does this mean in test_requirements.txt? 
nose
responses==0.3
BTW, what exactly could I see if running the tests successfully?

I would appreciate your help very much if you help me with those questions.

**Comment by domesticmouse** [comment]
Answering your questions:
1) Yes, this is a library for accessing the [Google Maps API Web Services](https://developers.google.com/maps/documentation/webservices/) from the Python programming language
2) I can see how `$ tox` would be confusing for a Windows 7 user. `$ tox` means to run the `tox` program from the command line. The `$` in question is a reference to the `bash` command line shell that is in common use on Linux and OSX computers.
3) Yes, I can see how the errors you are seeing would be confusing. There is a introduction to Python commond line programming for Python in [Python on Windows FAQ](https://docs.python.org/2/faq/windows.html). This is but the first step in a long chain of learning.
4) The `test_requirements.txt` file is a configuration for the `tox` build system. I suggest reading through this page on the [tox automation project](https://testrun.org/tox/latest/).

Programming is an art driven mainly by an unending desire to keep learning. I suggest you run up a Linux machine using either a virtual machine environment, or a [raspberry pi](https://www.raspberrypi.org/). Learning to master the `bash` command line will pay good dividends in a lifetime of programming.

**Comment by scarlettlee** [comment]
Thank you very much, domesticmouse! 
I'll take your advice.
