### ISSUE TITLE
Access behind Proxy

### ISSUE THREAD

**Issue by Bandit253** [googlemaps/google-maps-services-python#83]
I am behind an authenticated proxy server any clues on how to supply the server and credentials?

**Comment by stephenmcd** [comment]
I've just committed a change that allows you to pass through any of the `requests` args into the client, which includes support for proxy auth, so something like:

```
gmaps = googlemaps.Client(key='Add Your Key here', requests_kwargs={'auth': ...})
```

Check out the requests docs for all the details: http://www.python-requests.org/en/latest/api/#main-interface

We'll push out a new version shortly with this feature.
