### ISSUE TITLE
Searching for Chinese with http://maps.google.cn

### ISSUE THREAD

**Issue by nickytong** [googlemaps/google-maps-services-python#84]
Thank you for making this wonderful package.
Is it possible to use the Chinese version from http://maps.google.cn ?
I searched the term "金波银波" at http://maps.google.cn and this result is more meaningful than https://www.google.com/maps

Searching Chinese targets is described by Google at:
https://developers.google.com/maps/documentation/javascript/basics

Thank you very much!

**Comment by broady** [comment]
Did you try setting `language=zh-cn` and `region=cn` as an option?

https://developers.google.com/maps/documentation/geocoding/#language-param
https://developers.google.com/maps/documentation/geocoding/#RegionCodes

**Comment by nickytong** [comment]
After setting this option everything works like a charm!
Thank you!
