### ISSUE TITLE
add to anaconda distribution?

### ISSUE THREAD

**Issue by daviddou82** [googlemaps/google-maps-services-python#85]
can this project be added to the anaconda distribution?

**Comment by markmcd** [comment]
I think you'll need to suggest that to the Anaconda team - https://github.com/ContinuumIO/anaconda-issues/issues

**Comment by aviciimaxwell** [comment]
im sorry but im lost here what project are you talking about


2015-08-08 23:18 GMT+02:00 daviddou82 <notifications@github.com>:
