### ISSUE TITLE
requests > 2.6

### ISSUE THREAD

**Issue by ambrozic** [googlemaps/google-maps-services-python#89]
Hey guys,

I swear i searched all issues and could not find an answer.

Is there a reason why requests<=2.6 requirement still hasn't changed?

Cheers

**Comment by tapanpandita** [comment]
+1

**Comment by jonathan-golorry** [comment]
Can we get a release with this included ASAP? Some packages already require a newer version of requests than the old requirement allows.

**Comment by hodgesmr** [comment]
Came here to echo https://github.com/googlemaps/google-maps-services-python/issues/89#issuecomment-172725507 for a release.

**Comment by stephenmcd** [comment]
We'll aim to get a release out soon, but it's worth pointing out that in the meantime, `pip` will happily install a specific commit directly from GitHub:

http://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

So if you were to specify the latest commit in GitHub as your dependency, you'd be installing the exact same code base as you would if a new release went out, sans a version number change.

**Comment by stephenmcd** [comment]
2.4.3 is released now
