### ISSUE TITLE
Add "traffic-model" option to Distance Matrix and Directions

### ISSUE THREAD

**Issue by Gkreindler** [googlemaps/google-maps-services-python#97]
Can you please add the traffic-model = "pessimistic", "optimistic"  or "best-guess" (default) as a pass-through argument for Distance Matrix and Directions?

https://developers.google.com/maps/documentation/distance-matrix/intro#traffic-model

**Comment by stephenmcd** [comment]
Thanks for the report! I just pushed version 2.4.1 which resolves this.

**Comment by malwar** [comment]
Can you please update the developer guide for the correct parameter name "traffic-model" instead of "traffic_model"?

https://developers.google.com/maps/documentation/distance-matrix/intro#traffic-model

**Comment by rreis** [comment]
Hi all

It was not clear to how to do this in some Google API... or if it is
planned... For a travel mode, retrieve the estimated travel cost.

Thanks for helping,

A --> (Ricardo Reis) --> B
