### ISSUE TITLE
Traffic model bug? "optimistic" slower than "best-guess"

### ISSUE THREAD

**Issue by Gkreindler** [googlemaps/google-maps-services-python#99]
Hello, I found that traffic_model="optimistic" sometimes takes longer than traffic_model="best guess". I don't know if this is because of the library or because of Google Maps, but I thought I'd ask, because it makes me question the results using "optimistic" more generally. That is, maybe the results using "optimistic" are not reliable in general.

The graph plots the travel time using the three traffic_model options, for all departure times on a particular day (in the future). Note how during the night the "optimisitic" is slower than the other two.
![image](https://cloud.githubusercontent.com/assets/6221182/11506788/1c8f5420-981f-11e5-826d-71fc1bceec64.png)

Also, here is code that generates this for a particular leaving time.

Code output:
```
['Travel time from: 12.979572,80.25271 to 12.921726,80.230478']
['Departure time (local): 16 Dec 2015 03:42:02']
['Time, no traffic, minutes: 12.566666666666666']
['Time in traffic, minutes: 9.45']
['Time in traffic (optimistic), minutes: 10.45']
```

Code:
```
__author__ = 'Gabriel Kreindler, gek@mit.edu'

'''
This code shows that the traffic_model option sometimes generates counter-intuitive results.
The option traffic_model="optimistic" sometimes generates longer travel times compared to "best_guess" or "pessimistic".
(The latter is not shown here.)
'''

import googlemaps
import time
import calendar

# client
client = googlemaps.Client(key='KEY HERE')

# origin and destination
orig="12.979572,80.25271"
dest="12.921726,80.230478"

# query time
t1 = time.strptime("15 Dec 2015 22:12:02", "%d %b %Y %H:%M:%S")
nsec1 = calendar.timegm(t1)

# get offset
timezone_offset = client.timezone(orig, timestamp=nsec1)
timezone_offset_sec = timezone_offset['rawOffset']

# nice local time
t1_loc = time.gmtime(nsec1 + timezone_offset_sec) # local time
dep_time_local = time.strftime("%d %b %Y %H:%M:%S", t1_loc)


# get duration in traffic
dist = client.distance_matrix(orig, dest, departure_time=nsec1, mode="driving")

# parse
temp = dist["rows"][0]["elements"][0]
assert temp["status"]=="OK"
dist_output = temp["distance"]["value"]
dur_output = temp["duration"]["value"]  # duration
dur_intraffic_output = temp["duration_in_traffic"]["value"]

# get duration in traffic
dist = client.distance_matrix(orig, dest, departure_time=nsec1, mode="driving", traffic_model="optimistic")

# parse
temp = dist["rows"][0]["elements"][0]
assert temp["status"]=="OK"
dur_intraffic_opt_output = temp["duration_in_traffic"]["value"]

print(['Travel time from: ' + orig + ' to ' + dest])
print(['Departure time (local): ' + dep_time_local])
print(['Time, no traffic, minutes: ' + str(dur_output/60)])
print(['Time in traffic, minutes: ' + str(dur_intraffic_output/60)])
print(['Time in traffic (optimistic), minutes: ' + str(dur_intraffic_opt_output/60)])
```

**Comment by stephenmcd** [comment]
I've filed this as an issue in the distance matrix API issue tracker:

https://code.google.com/p/gmaps-api-issues/issues/detail?id=8972

You might like to subscribe to that to receive feedback.

**Comment by domesticmouse** [comment]
I had a quick chat with the engineer responsible, and his stance is that this is working as intended. Best guess is using a prediction model that utilises current traffic as an input into the prediction model, while both optimistic and pessimistic ignore current traffic. 

I can understand your questioning of the prediction model's results, but it is worth remembering that a prediction model is only ever as good as the data it has. The problematic time of day is early in the morning when there are few cars on the road, so we have very little training data. During the working day, when we have lots of data to learn over, then the predictions are a lot more robust.

The outcome here is please use best guess. The optimistic and pessimistic options are really meant for advanced usage only, and come with a bunch of usage warnings.

**Comment by Gkreindler** [comment]
Thank you Brett, this is very useful!

One question: what do you mean that the "best guess" prediction model using current traffic as input? In the example above the query time is in the (distant) future, so current traffic (at the time of the query) should not enter into the model, right? 
However, I understand the general point of data scarcity. I would have thought something like smoothing is done differently for the different traffic models.

Are the usage warning for optimistic and pessimistic documented somewhere publicly?

Many thanks!

**Comment by domesticmouse** [comment]
The live traffic signal is more heavily weighted the closer requested prediction time is to now.

As to publicly documenting the usage warnings, I'm currently contemplating how best to document that on developers.google.com/maps right now. Any suggestions gladly accepted =)

**Comment by Gkreindler** [comment]
Using a departure time on Dec **2016** still gives the same result (opt>pess), so I'm not sure the live traffic is driving this.

The most important thing for me (as an aspiring advanced user) in terms of usage description is having a basic understanding of the underlying model. What do the best_guess, optimistic and pessimistic predictions do? Are the last two *approximately* percentiles of the historical distribution of travel times? If so, which percentiles? Mentioning that best_guess uses live traffic to some extent was (useful) news to me. Does the model include provisions for special dates (eg New Year's eve) or only day of the week? Is "best_guess" the predicted average/median travel time?

You mention that the prediction is less reliable when there is little data (ie at night, or at less traveled locations). What does the model default towards in these cases? Is it smoothed over space and time of day?

Thank you again for your help!

**Comment by domesticmouse** [comment]
It sounds like you are expecting this to be a statistical prediction model. I'd suggest you do some research into [TensorFlow](https://www.tensorflow.org/) to get a feeling for the styles of models we use to make sense of the world.

**Comment by Gkreindler** [comment]
Thank you, this is very useful.

**Comment by domesticmouse** [comment]
Thank you again for your investigation, we have now changed the backend to report more sane predictions for these problematic cases.

**Comment by Gkreindler** [comment]
Hello,

Thank you for making this change, this is very useful to hear.

Kind regards,
Gabriel
